bazelbuild/rules_docker

- README.md
This is modeled after rules_go
> Expand the badges displayed

- docker/BUILD
- docker/build_test.sh
- docker/create_image_config.py
- docker/rewrite_json.py
- docker/testdata/BUILD
The argparse bug: https://bugs.python.org/issue14364
Fixes https://github.com/bazelbuild/rules_docker/issues/48
> Add special handling to work around an arparse bug.

- README.md
- docker/build.bzl
Fixes: https://github.com/bazelbuild/rules_docker/issues/59
> Fixes the links to Dockerfile documentation.

- docker/BUILD
- docker/build_test.sh
- docker/bundle.bzl
- docker/incremental_load.sh.tpl
- docker/layers.bzl
Fixes https://github.com/bazelbuild/rules_docker/issues/35
> Support stamp variable expansion with 'bazel run'

- docker/build_test.sh
I fixed a spacing issue I found.
> Fix spacing

- README.md
This also adds a detailed section on how to vary tag names using stamping and make variables.
Thanks to @ixdy for a lot of the content that went into this.
Fixes https://github.com/bazelbuild/rules_docker/issues/65
> This documents the stamp option on docker_push.

- docker/incremental_load.sh.tpl
Fixes https://github.com/bazelbuild/rules_docker/issues/79
> Fix incremental loading of `docker_import`.

- docker/incremental_load.sh.tpl
Fixes https://github.com/bazelbuild/rules_docker/issues/79
> Fix the right line this time.

- docker/incremental_load.sh.tpl
> incremental_load.sh.tpl: Use standard tar syntax.

- docker/contrib/with-defaults.bzl
Fixes: https://github.com/bazelbuild/rules_docker/issues/64
> Create a contrib rule for creating docker_push defaults.

- docker/docker.bzl
Fixes https://github.com/bazelbuild/rules_docker/issues/104
> Upgrade to v0.0.13 of google/containerregistry

- docker/build_oci_test.sh
- docker/build_test.sh
- docker/docker.bzl
Fixes: https://github.com/bazelbuild/rules_docker/issues/140
> Fix the Labels field in the image metadata for v2.2

- README.md
Fixes: https://github.com/bazelbuild/rules_docker/issues/147
> Add links to the ECR/AzureCR cred helper repos.

- docker/incremental_load.sh.tpl
- testing/e2e.sh
Related to: https://github.com/bazelbuild/rules_docker/issues/148
> Make sure we always use an absolute path for ${RUNFILES}

- README.md
- docker/BUILD
- docker/build.bzl
- docker/build_test.sh
- docker/create_image_config.py
- docker/testdata/BUILD
Fixes: https://github.com/bazelbuild/rules_docker/issues/150
> Add support for stamping various pieces of image metadata.

- docker/build_test.sh
- docker/contrib/java/image.bzl
- docker/testdata/BUILD
Fixes: https://github.com/bazelbuild/rules_docker/issues/157
> Make java_image respect jvm_flags

- docker/contrib/push-all.bzl
- docker/contrib/push-all.sh.tpl
Fixes: https://github.com/bazelbuild/rules_docker/issues/163
> Make push-all fail if any of the pushes fail.

- docker/docker.bzl
- oci/oci.bzl
This simplifies the import into the mono-repo.
> Tweak the manner in which we alias things.

- README.md
Fixes: https://github.com/bazelbuild/rules_docker/issues/168
> Update documented release to reflect v0.3.0 cut

- README.md
- WORKSPACE
- scala/BUILD
- scala/image.bzl
- testdata/BUILD
- testdata/Binary.scala
- testing/e2e.sh
This does not yet take advantage of layering.
> Add a very basic scala_image rule.

- README.md
- WORKSPACE
- groovy/BUILD
- groovy/image.bzl
- testdata/BUILD
- testdata/Binary.groovy
- testing/e2e.sh
This does not yet take advantage of layering.
Builds on: https://github.com/bazelbuild/rules_docker/pull/185
> Add a very basic groovy_image rule

- README.md
- WORKSPACE
- rust/BUILD
- rust/image.bzl
- testdata/BUILD
- testdata/main.rs
- testing/e2e.sh
Builds on: https://github.com/bazelbuild/rules_docker/pull/186
> Add a very basic rust_image rule

- README.md
- WORKSPACE
- d/BUILD
- d/image.bzl
- testdata/BUILD
- testdata/main.d
- testing/e2e.sh
https://github.com/bazelbuild/rules_docker/pull/187
> Add a very basic d_image rule

- container/incremental_load.sh.tpl
> appropriately pass multiple command line arguments

- container/BUILD
- tools/BUILD
These were introduced by a change to buildifier or Bazel.
> Fix new buildifier errors.

- container/container.bzl
> Update to the latest release of google/containerregistry.

- groovy/image.bzl
- scala/image.bzl
- testdata/BUILD
- testdata/Library.groovy
- testing/e2e.sh
Add fine-layering support to `rules_groovy`.
This is based on my PR that does that same for `rules_scala`.
> Groovy sandwich

- container/container.bzl
https://github.com/google/containerregistry/releases/tag/v0.0.23
> Update to containerregistry v0.0.23

- java/image.bzl
- lang/image.bzl
The `+` operator on dicts is deprecated and will be removed.
> Remove usages of `+` on dicts

- contrib/passwd.bzl
Cherrypicking @schoren's commit onto my branch.
> using better approach to file output

- container/image.bzl
- java/image.bzl
When we launch the container...
> Always run with host networking.

- container/container.bzl
> Update to containerregistry v0.0.26

- README.md
- container/BUILD
- container/create_image_config.py
- container/image.bzl
- container/image_test.py
- testdata/BUILD
Fixes: #155 
Signed-off-by: Jake Sanders <jsand@google.com>
> Allow for users to declare explicit build timestamps

- README.md
> Use http_archive instead of git_repository in examples

- container/image_test.py
- contrib/passwd.bzl
Forgot to add permissions mode to passwd_tar rule.
@erain one more favor from you!
> Add file permissions attribute to passwd_tar

- container/container.bzl
This brings python3 compatibility and should fix #293
> Update containerregistry to v0.0.28

- WORKSPACE
- nodejs/image.bzl
Seems the latest rules_nodejs changed the packages around the nodejs bin. This should fix it.
> Fix for latest rules_nodejs.

- container/image_test.py
- java/image.bzl
- testdata/BUILD
I am not sure about the test cases for Scala and Groovy since the new logic should be covered by just the java test suites.
For the sake of completeness I added them anyway.
Resolves #468
> Expand $location in jvm_flags

- cc/cc.bzl
- go/go.bzl
- java/java.bzl
- java/jetty.bzl
- nodejs/nodejs.bzl
- python/python.bzl
- python3/python3.bzl
https://github.com/bazelbuild/rules_docker/issues/479
https://github.com/bazelbuild/rules_docker/issues/477
> update deps for lang_image bases

- WORKSPACE
* fixes https://github.com/bazelbuild/rules_docker/issues/497
> update pin to rules_groovy

- container/container.bzl
> Fix @bazel_source archive sha.

- WORKSPACE
- container/image.bzl
- container/providers.bzl
- java/image.bzl
- lang/image.bzl
- nodejs/image.bzl
- testdata/BUILD
- testing/e2e.sh
> Expose docker run info in container_image rule.

- cc/cc.bzl
- go/go.bzl
- java/java.bzl
- java/jetty.bzl
- nodejs/nodejs.bzl
- python/python.bzl
- python3/python3.bzl
> Update distroless bases.

- .travis.yml
- container/container.bzl
> Update containerregistry release version.

- README.md
Signed-off-by: David Gageot <david@gageot.net>
> Fix typo in setup section

- .gitignore
Ignore vim swap files in rules_docker git repo
> Gitignore vim swap

- scala/image.bzl
> Respect tags attribute for all rules in scala_image

- README.md
> Update Authentication section.

- java/image.bzl
For #523, modeled on the recent similar change to the scala rules
> Pass through tags to targets created by java_image

- README.md
- toolchains/docker/readme.md
Provides documentation on how to write new rules or extend existing rules that use the docker toolchain
> Add documentation for using the docker toolchain rules

- .bazelci/presubmit.yml
They have been upstreamed into Buildkite config.
> Remove extra build/test flags.

- tests/docker/BUILD
- tests/docker/configs/java_entrypoint.yaml
- tests/docker/configs/java_partial_entrypoint.yaml
- tests/docker/java/BUILD
- tests/docker/java/configs/java_image_entrypoint.yaml
- tests/docker/java/configs/java_partial_entrypoint.yaml
- tests/docker/java/configs/java_runfiles_as_lib_image_entrypoint.yaml
- tests/docker/java/configs/java_runfiles_image_entrypoint.yaml
- tests/docker/java/configs/simple_java_entrypoint.yaml
* moving more tests to use container image
* refactoring tests to java directory
* adding env variables check for all java image tests
> Move more java image tests to container image

- README.md
- container/container.bzl
- toolchains/docker/BUILD
- toolchains/docker/BUILD.tpl
- toolchains/docker/readme.md
- toolchains/docker/toolchain.bzl
> Docker toolchain autoconfiguration using 'which'

- toolchains/docker/BUILD
Mirroring pending internal change
> Remove x86_64 from the target constraints from the docker toolchain

- .bazelci/presubmit.yml
fixes https://github.com/bazelbuild/rules_docker/issues/615
> add build_flags to fix rules_docker upstream CI

- container/flatten.bzl
- container/image.bzl
- container/layer.bzl
- container/layer_tools.bzl
- container/push.bzl
- contrib/push-all.bzl
- java/image.bzl
- skylib/zip.bzl
> Migrate out of the old action API in Bazel

- lang/image.bzl
- tests/docker/nodejs/BUILD
- tests/docker/nodejs/configs/nodejs_image_empty_list_args.yaml
- tests/docker/nodejs/configs/nodejs_image_list_with_empty_string_args.yaml
- tests/docker/nodejs/configs/nodejs_image_none_args.yaml
> Properly set `cmd` from `args` in lang images.

- .bazelci/presubmit.yml
- WORKSPACE
- container/incremental_load.sh.tpl
- container/layer.bzl
- toolchains/docker/toolchain.bzl
* Also fix CI
* enable passing a path to docker binary in workspace rule (buildkite CI no longer runs in host env that has docker installed)
* disable some tests that run on buildkite ci with local execution that are failing since CI runs on docker, will need to fix those later
> fix typo + fix CI

- container/BUILD
- container/image_test.py
- testdata/BUILD
- testdata/stamp_info.bzl
- testing/e2e.sh
- tests/docker/cc/BUILD
- tests/docker/cc/configs/BUILD
- tests/docker/cc/configs/cc_image.yaml
- tests/docker/go/BUILD
- tests/docker/go/configs/BUILD
- tests/docker/go/configs/go_image.yaml
- tests/docker/groovy/BUILD
- tests/docker/groovy/configs/BUILD
- tests/docker/groovy/configs/groovy_image.yaml
- tests/docker/java/BUILD
- tests/docker/java/configs/java_partial_entrypoint.yaml
- tests/docker/java/configs/java_runfiles_image.yaml
- tests/docker/java/configs/simple_java_entrypoint.yaml
- tests/docker/python/BUILD
- tests/docker/python/configs/BUILD
- tests/docker/python/configs/py_image.yaml
- tests/docker/python3/BUILD
- tests/docker/python3/configs/BUILD
- tests/docker/python3/configs/py3_image.yaml
- tests/docker/rust/BUILD
- tests/docker/rust/configs/BUILD
- tests/docker/rust/configs/rust_image.yaml
- tests/docker/scala/BUILD
- tests/docker/scala/configs/BUILD
- tests/docker/scala/configs/scala_image.yaml
Migrating more tests to tests/docker
File existence tests:
* cc
Metadata tests:
* cc
* py
* py3
* go
* rust
* scala
* groovy
> Migrate more tests to tests/docker

- .bazelci/presubmit.yml
- container/image.bzl
- testdata/BUILD
- tests/docker/BUILD
- tests/docker/configs/set_env_make_vars.yaml
This addresses https://github.com/bazelbuild/rules_docker/issues/670
I haven't figured out how to write a test that can set Make variables. Please let me know what is a good way to test this.
> Expand make variables in env field

- README.md
Docs on how to use custom authentication credentials with container_pull and push
> Toolchain auth docs

- cc/cc.bzl
- go/go.bzl
- java/java.bzl
- java/jetty.bzl
- nodejs/nodejs.bzl
- python/python.bzl
- python3/python3.bzl
> Run update_deps.sh to update latest security fixes from distroless.

- WORKSPACE
- java/image.bzl
* Upgrade rules_go version.
* Fix --incompatible_depset_is_not_iterable.
> Fix Bazel incompatible issues.

- .bazelci/presubmit.yml
- WORKSPACE
- toolchains/BUILD
Rbe_autoconfig platform is now in use by BuildKite CI:
https://github.com/bazelbuild/continuous-integration/pull/551
> use rbe_autoconfig platform

- container/image.bzl
Per comment https://github.com/bazelbuild/rules_docker/pull/648/files#r263609718
> Fix attribute type for inputs.

- contrib/dockerfile_build.bzl
Use the supplied Dockerfile for docker build command, so don't copy the Dockerfile into the workspace.
The docker bulid command needs to run using the supplied Dockerfile because the Dockerfile may refer to relative paths in its ADD, COPY and WORKDIR instructions.
> Use the supplied Dockerfile for docker build command

- repositories/repositories.bzl
> Update httplib2 to v0.12.1

- .bazelci/presubmit.yml
- WORKSPACE
Checking CI will pass before this is reviewed. Will let you know once it passes to review.
> enable tests that require XZ on rbe

- .bazelci/presubmit.yml
- container/BUILD
- container/build_tar.py
- repositories/repositories.bzl
* Also remove some skipped targets from buildkite config that I forgot to remove in previous PR.
> remove TODO for bazel_source pin

- container/go/cmd/puller/BUILD
- container/go/cmd/puller/puller.go
Now that this exists in the internal codebase.
> Add back reference to cache in new go puller binary

- container/new_pull.bzl
Now that our internal system supports caching again.
> Update new_pull.bzl to include cache handling

- testing/e2e.sh
- testing/e2e/bazel_run_docker.sh
- testing/e2e/docker_run_flags.sh
- testing/e2e/groovy_image.sh
- testing/e2e/java_image.sh
- testing/e2e/launcher.sh
- testing/e2e/nodejs_image.sh
- testing/e2e/py_image.sh
- testing/e2e/scala_image.sh
- testing/e2e/test_groovy_image.yaml
- testing/e2e/test_java_image.yaml
- testing/e2e/test_launcher.yaml
- testing/e2e/test_py_image.yaml
- testing/e2e/test_scala_image.yaml
- testing/e2e/util.sh
* Noted which test cannot move from e2e.sh for now and why.
> Even more tests moved to GCB from e2e

- container/go/cmd/puller/puller.go
Removed old format options and update docs.
> Update new puller binary

- .bazelci/presubmit.yml
- container/new_load.bzl
- container/new_pull.bzl
- repositories/repositories.bzl
> Enable using Darwin binary.

- WORKSPACE
- tests/container/BUILD
> Pin containers that are used for digest tests.

- WORKSPACE
- tests/container/scala/configs/scala_image.yaml
fixes issues in https://github.com/bazelbuild/rules_docker/pull/991
> update rules scala and fix test

- go/image.bzl
- go/static.bzl
- tests/container/go/BUILD
- tests/container/go/configs/go_static_image.yaml
- update_deps.sh
> Use distroless/static base for go containers when pure is "on"

- cc/cc.bzl
- go/go.bzl
- go/static.bzl
- java/java.bzl
- java/jetty.bzl
- nodejs/nodejs.bzl
- python/python.bzl
- python3/python3.bzl
https://github.com/bazelbuild/rules_docker/issues/1068
> update base images

- README.md
- toolchains/docker/toolchain.bzl
addresses https://github.com/bazelbuild/rules_docker/issues/1072
> clarify docs for use of client_config

- README.md
also addresses https://github.com/bazelbuild/rules_docker/issues/1072
> Clarify when not to use custom pull rule

- toolchains/docker/BUILD
Reverts bazelbuild/rules_docker#1084
> Revert "Add xz_path to default toolchain"

- toolchains/docker/BUILD
See https://github.com/bazelbuild/rules_docker/pull/1092
> Add xz to default toolchain again 

- WORKSPACE
- tests/container/groovy/configs/groovy_image.yaml
> Update rules_groovy pin

- container/new_pull.bzl
> new_pull: expose puller_darwin and _linux attr for testing

- container/image.bzl
Following advice from: 
https://docs.bazel.build/versions/master/skylark/performance.html#use-ctxactionsargs-for-command-lines
> use ctx.args in image.bzl

- container/flatten.bzl
- container/image.bzl
- container/layer.bzl
- container/layer_tools.bzl
- container/new_push.bzl
- docker/package_managers/install_pkgs.bzl
Following up on https://github.com/bazelbuild/rules_docker/pull/1156
> more use ctx.args

- container/flatten.bzl
- container/image.bzl
- container/layer.bzl
- container/layer_tools.bzl
- container/new_push.bzl
- docker/package_managers/install_pkgs.bzl
Reverts bazelbuild/rules_docker#1157
Need to test this with the new join_layers properly and re-send
> Revert "more use ctx.args"

- container/flatten.bzl
- container/image.bzl
- container/layer.bzl
- container/layer_tools.bzl
- container/new_push.bzl
- docker/package_managers/install_pkgs.bzl
Includes fixes that led to https://github.com/bazelbuild/rules_docker/pull/1158
> More use ctx args

- repositories/go_repositories.bzl
Pins to go containerregistry after commit with fix for https://github.com/bazelbuild/rules_docker/issues/1193
> update go containerregistry for #1193

- repositories/go_repositories.bzl
Pulls in https://github.com/google/go-containerregistry/pull/573
> Update go-containerregistry to fix panic in image tarball writer

- repositories/go_repositories.bzl
To pick up https://github.com/google/go-containerregistry/pull/582 that adds debug logs
> update go containerregistry

- README.md
For the benefit of https://github.com/bazelbuild/rules_docker/issues/300#issuecomment-520451066
> Add new adopter

- README.md
Added documentation for empty_dirs on container_layer.
> Added Documentation for container_layer for empty_dirs

- container/push.bzl
- contrib/push-all.bzl
Reverts bazelbuild/rules_docker#1353
> Revert "Add robot_email attr to container push bzl rules"

- README.md
> Add Canva to adopters list

- contrib/repro_test.bzl
Deleting directories created by repro tests can no longer be done inside the container.
> fix repro tests

- tests/container/BUILD
> update alpine sha

- nodejs/image.bzl
> pass tag/visiblity to nodejs_image dep layers

- container/build_tar.py
- container/image_test.py
- repositories/repositories.bzl
- tests/container/BUILD
This reverts commit 166b6bc2856f62dd263b1e7635f3a331dc325230.
> Revert "Enable mtime preservation in tar file building process (#1485)"

- container/build_tar.py
- container/layer.bzl
Please let me know if there's a good place to test this new option.
> Allow users to opt into mtime preservation

- WORKSPACE
- contrib/repro_test.bzl
- repositories/repositories.bzl
- tests/contrib/BUILD
> Update go dependency & Bazel test image

- container/incremental_load.sh.tpl
This image could potentially be large, and we are streaming anyway as the comment indicates.
> Dont write incremental tarball to disk

- README.md
> Update pip setup in README

- toolchains/docker/BUILD
> Make toolchain_type public

- container/go/cloudbuild.yaml
First step towards addressing #1155
> Add Linux ARM64 go pusher and loader binaries to cloudbuild

- contrib/BUILD
- contrib/test.bzl
- repositories/repositories.bzl
Upgrade to 1.9.1 and include arm64 support.
cc @nkubala @nlopezgi
> Plumb constraints thru container_test

- testing/e2e.sh
In anticipation of:
https://github.com/google/go-containerregistry/pull/827
> Relax error string matching

- docker/package_managers/download_pkgs.bzl
This resolves a bug on my system.
> Improve portability of download_pkgs genrule bash

- contrib/test.bzl
> Select the structure_test_executable for the execution platform

- testing/examples/run_instruction_arbitrary/BUILD
- testing/examples/run_instruction_arbitrary/Dockerfile
This should allow us to start testing the nonhermetic Dockerfile &
BUILD rules that allow users to specify commands to run/build in the
docker daemon.
> Fix URL used to download pip in examples/tests.

- README.md
> Only display status for builds on `master`

- .gitignore
> Ignore .ijwb folder from git

- docker/package_managers/README.md
> fix: typo in docker/package_managers/README.md

- docker/package_managers/install_pkgs.bzl
I need more time to debug this but more context is here:
https://github.com/bazelbuild/rules_docker/issues/1872
> WIP: Reordering this dict somehow fixes !1872.

- repositories/requirements-pip.txt
- tests/contrib/BUILD
This reverts commit 359898dbb45cffcf7e09c2a20d331e96ae3ae543.
> Revert "Bump pyyaml from 5.1 to 5.4 in /repositories"

- container/load.bzl
> container_load: use cfg="exec" instead of cfg="host"

- docs/BUILD
- docs/container.md
Avoids people sending PRs against generated content
> Add generated comment in generated file

- WORKSPACE
- kotlin/image.bzl
- tests/container/kotlin/configs/kt_jvm_image.yaml
The current `master` branch is still using `rules_kotlin` from a very old version.
`rules_kotlin` version has been updated to the latest release, `v1.5.0`.
Latest release page for `rules_kotlin`: https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.5.0
> Update rules kotlin

- README.md
> We have found some maintainers!

- container/go/cmd/pusher/pusher.go
This should reduce "use of closed network connection" errors due to too
many idle connections. Because we only expect to reach a couple hosts
during pushes anyway, this should be safe.
Currently, the value defaults to 2. This change sets it to half the
total IdleConnsPerHost, which defaults to 100.
New value is 100 / 2 = 50.
Only 2 idle connections are permitted per host, which can lead to issues when pushing many layers.
Issue Number: https://github.com/bazelbuild/rules_docker/issues/1989
Allow 50 idle connections per host.
> Set MaxIdleConnsPerHost for pushes

- container/go/cmd/zipper/zipper.go
- container/go/pkg/compat/write.go
Files are not properly closed after being read/written
Properly closing them
> Properly close files after read/write

- docker/util/run.bzl
Bazel action mnemomics are now available for easy targeting of specific actions
> Add missing RunAnd* mnemonics

- container/BUILD
- container/build_tar.py
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
The current import implicitly relies on the behavior where every immediate sub-directory under the runfiles root is added to `PYTHONPATH`
Removes this assumption, which fixes an incompatibility with `--noexperimental_python_import_all_repositories`
see https://github.com/bazelbuild/rules_python/issues/792
> Fix import (fixes --noexperimental_python_import_all_repositories)

- go/image.bzl
- testing/e2e/go_image.sh
- tests/container/go/BUILD
This is a follow-up for 7d34678afa33909951b4e936574efab815411cfd
> go_image: implement `tag_name`

- container/push.bzl
- [na] Tests for the changes have been added (for bug fixes / features)
> Add comment about overriding container_push destination

- README.md
People are still using rules_docker
People should start using rules_oci
> deprecate rules_docker

- README.md
Updates readme for unarchived status.
> Update README to clarify maintenance status of rules_docker
