README.md
Fixes https://github.com/bazelbuild/rules_docker/issues/4
=> Add a reference to google/containerregistry

.travis.yml
Supposedly [all Travis runtimes include the go compiler](https://docs.travis-ci.com/user/ci-environment/#Runtimes). Let's see if that's true?
=> Run buildifier on travis

README.md, docker/BUILD, docker/build_test.sh, docker/bundle.bzl, docker/join_layers.py, docker/layers.bzl, docker/testdata/BUILD
This allows using workspace status information (such as git describe) in image tags. To differentiate from make variables (and laziness), I'm using python formatting syntax, e.g. `{STABLE_BUILD_USER}` or `{MY_CUSTOM_VAR}`.
This is basically an implementation of what I was describing in https://github.com/bazelbuild/rules_docker/issues/3#issuecomment-297563224.
I think it'd work for what I need for kubernetes right now, though I'm not sure if this is the correct implementation, e.g. does it makes sense to do the stamping in `docker_bundle`? Should it also be supported in `docker_build` and/or `docker_push`? What things should be "stampable"? Do we want to be able to embed stamping info in image labels? (I might in the future, e.g. embed revision/other build data.)
(`docker_push` actually …
=> Add stamp option to docker_bundle rule

docker/create_image.py, docker/create_image_config.py, docker/docker.bzl, docker/join_layers.py
Leverage some of the new facilities to avoid gzip whenever possible during docker_build.
=> Upgrade to google/containerregistry v0.0.4

docker/docker.bzl
Fixes: https://github.com/bazelbuild/rules_docker/issues/15
=> Upgrade to v0.0.5 of the google/containerregistry tooling.

docker/build_oci_test.sh, docker/build_test.sh, docker/testenv.sh
This verbosity leads to additional complexity to strip it out and is (I believe) causing these tests to fail on OSX because the output is differently shaped.
=> Remove verbosity on tar in build_{oci_}test.sh

docker/BUILD, docker/build_test.sh, docker/contrib/BUILD, docker/contrib/with-tag.bzl, docker/testdata/BUILD
Fixes: https://github.com/bazelbuild/rules_docker/issues/8
=> Expose a derivative of docker_build that tags as well.

.travis.yml, docker/create_image.py, docker/docker.bzl, docker/join_layers.py, testing/e2e.sh
Switch to using the new relaxed naming to fix the linked issue.
Fixes: https://github.com/bazelbuild/rules_docker/issues/28
=> Upgrade to v0.0.7 of google/containerregistry

README.md
I don't think this example intended to provide a list for `base`.
Fixes #42
=> Update README.md for docker_build example

docker/BUILD
Fixes https://github.com/bazelbuild/rules_docker/issues/49
=> Add docker/__init__.py so that "docker" dir is always considered a package

docker/docker.bzl, docker/push-tag.sh.tpl, docker/push.bzl, docker/testdata/BUILD
=> Add support for stamping docker_push

README.md
We lost the discussion of `bazel run` semantics, and getting the full tarball, both of which can be useful for local iteration.
Fixes https://github.com/bazelbuild/rules_docker/issues/58
=> Restore some of the old documentation.

docker/push.bzl
Add mandatory=True to the image label of the push command.
=> fix(push): set image attr as mandatory

README.md, docker/BUILD, docker/docker.bzl, docker/filetype.bzl, docker/import.bzl, docker/testdata/BUILD, docker/zip.bzl, testing/e2e.sh
`docker_import` imports the constituent elements of an image into our intermediate form.
This will shortly become an implementation detail of `docker_pull`, but in mono-repo scenarios it can be used to more efficiently commit an image to avoid expensive legacy `ExtractConfig` actions.
=> Introduce a docker_import rule.

docker/incremental_load.sh.tpl
Tried running on my mac and ran into a few issues, these are the fixes for them.
Have kept things separate in case you only wanted parts.
`27c3d4c` - Feels like a bit of a hack but seemed the easiest approach was to ask the user to install GNU tar rather than doing something more complex.  Makes the assumption that GNU tar won't change its version output.
`46d0b43`- `&|` is not portable and was giving me an unexpected token error.  Couldn't see why stdout+stderr needed to be piped though, so changed that up to be just a pipe of stdout.  If there's something I haven't considered here, let me know and I'll change it to the unabbreviated `2>&1 |`.
=> Improve mac compatibility/portability of incremental_load script

docker/docker.bzl
Fixes: https://github.com/bazelbuild/rules_docker/issues/55
Fixes: https://github.com/bazelbuild/rules_docker/issues/77
=> Add limited support for overriding and excluding dependencies.

README.md
The build badges by architecture for Bazel CI will soon no longer works, refer to the parent configuration instead.
=> Update the build badge for Bazel CI

docker/BUILD, docker/build.bzl, docker/build_tar.py
This forks `build_tar.py` from the Bazel repo in two steps.
I'm going to patch the Bazel repo to do the same thing as here, but I don't want to wait for another Bazel release to leverage this, so I'm forking things for now.
=> Fork build_tar.py

docker/build.bzl, docker/bundle.bzl, docker/import.bzl
`set` is a deprecated alias of `depset` and will be removed soon.
Also, they are not hashsets, if you need a hashset you can use a dict with empty values.
=> Rename set to depset

WORKSPACE, docker/BUILD, docker/build.bzl, docker/build_tar.py, docker/build_test.sh, docker/contrib/cc/BUILD, docker/contrib/cc/image.bzl, docker/contrib/common/BUILD, docker/contrib/common/lang-image.bzl, docker/contrib/go/BUILD, docker/contrib/go/image.bzl, docker/contrib/java/BUILD, docker/contrib/java/image.bzl, docker/contrib/python/BUILD, docker/contrib/python/image.bzl, docker/contrib/with-defaults.bzl, docker/docker.bzl, docker/filetype.bzl, docker/push.bzl, docker/testdata/BUILD, docker/testdata/Binary.java, docker/testdata/Library.java, docker/testdata/Servlet.java, docker/testdata/cc_image.cc, docker/testdata/cc_image_library.cc, docker/testdata/cc_image_library.h, docker/testdata/py_image.py, docker/testdata/py_image_library.py, testing/e2e.sh
This change is a first-cut at attempting a `foo_image` rule that directly assembles a Docker image compatible with `foo_binary`, but leveraging a sharded archive format (vs. a mono-archive format like [PAR](https://github.com/google/subpar) or "deploy JAR")
The advantage of the sharded archive format is simple:  **We want to translate build-time incrementality into redeployment incrementality.**
By enabling the partitioning of dependencies into their own layers, in a binary agnostic fashion, we enable:
1. sharing of those dependencies across different images that depend on them
1. no republishing of those dependencies' layers when they haven't changed
1. no repulling unchanged dependencies' layers
In this model, what gets repushed/repulled can be made a direct function of Bazel's …
=> First cut at a foo_image rule

docker/docker.bzl
Fixes: https://github.com/bazelbuild/rules_docker/issues/111
Fixes: https://github.com/bazelbuild/rules_docker/issues/39
=> Upgrade to the v0.0.14 of google/containerregistry

docker/contrib/java/image.bzl, docker/testdata/BUILD, testing/e2e.sh
This is to avoid an overly strict check in Bazel when a JAR built with java_library is being turned into a binary via runtime_deps + main_class, when there should be no `srcs` or `deps` kwargs.
=> Avoid passing an empty list for deps, when there are no deps.

docker/build.bzl, docker/contrib/common/lang-image.bzl, docker/contrib/java/image.bzl, docker/incremental_load.sh.tpl, docker/layers.bzl, testing/e2e.sh
This makes the `bazel run` behavior on `docker_build` configurable and opts `foo_image` into running the container when the target is `bazel run`.
This does not change the default for `docker_build`, but users can now opt into it via `legacy_run_behavior = False`.
=> Run the container when `bazel run` on an image.

docker/build_test.sh, docker/contrib/java/image.bzl
Fixes: https://github.com/bazelbuild/rules_docker/issues/120
=> Allow classpath to be passed as a file.

docker/contrib/push-all.bzl
Simple PR to perform push-all in parallel.
Not super stoked about more reliance on bash (is there a better way to to this that means there's no bash usage? maybe building a bin for multi pushing or updating `google/containerregistry` to accept multiple images).
However this works for now and reduces push time for ~25 (unchanged) images from ~45 seconds to ~3 seconds.
=> Run push commands in push-all in parallel

docker/testdata/BUILD
This enables additional internal tests to build open this testdata.
=> Make testdata public

README.md
Currently, these links go to the examples, and you have to scroll down to find the full docs.
=> Link to docs at top of README

docker/build.bzl, docker/build_test.sh, docker/contrib/common/lang-image.bzl, docker/contrib/java/image.bzl
This introduces a new (internal-only for now) argument to the `docker_build` implementation that allows rules to pass a dictionary mapping from the path in the filesystem to a Bazel `File` object to place there.
The common `foo_image` implementation now consumes this in the refactored version to fix how files are being laid out.
I [first noticed](https://github.com/bazelbuild/rules_docker/issues/106) this with `java_image`, which still has this problem, but because we can just construct the `--classpath` argument appropriately it isn't really a correctness issue there (so I've punted on fixing this for now, since it's cosmetic).
With these changes, I am finally able to put together a layered Python GRPC example for `rules_k8s`!
Fixes: https://github.com/bazelbuild/rules_docker/issues/139
=> Refactor the way we pass files to the core docker_build for foo_image

docker/BUILD, docker/build_test.sh, docker/docker.bzl, docker/flatten.bzl, docker/testdata/BUILD
This adds a new rule that takes a `docker_build` image and produces a flattened tarball of the filesystem (`:foo.tar`) and extracts the image's metadata (`:foo.json`).
Fixes: https://github.com/bazelbuild/rules_docker/issues/145
=> Upstream the docker_flatten rule.

docker/contrib/push-all.bzl, docker/docker.bzl, docker/pull.bzl, docker/push.bzl
Switch to explicitly invoking Python when invoking PAR files in WORKSPACE phase.
Switch to consuming `py_binary` targets when invoking Python tooling in BUILD phase.
This is all working towards making rules_docker more portable, but doesn't completely resolve [this](https://github.com/bazelbuild/rules_docker/issues/136)
=> Python all the things

docker/build_test.sh, docker/contrib/common/lang-image.bzl, docker/contrib/java/image.bzl
This is the cosmetic portion of my prior change.  This doesn't affect correctness because we were making the bad paths match between the layout and the classpath previously.
That said, if you look at the diff in `build_test.sh` you can see that before the paths made no sense, and now all the things are rooted in their workspace's layout.
=> Bring sanity to java_image paths

docker/contrib/push-all.bzl
Without this push-all silently fails because "wait" is not checking exit statuses.
I will open an issue to track that, but wanted to fix the breakage from my recent change first.
=> Fix the runfiles path of the subcommands of push-all.bzl

README.md, container/BUILD, container/image_test.py, container/import.bzl, testdata/BUILD
This allows to let the rule decide if it needs the layers compressed or not. If one form is preferred over the other, it can be documented as such.
An added bonus is that the container_load rule can be made faster by passing on uncompressed layers instead of using python's gzip library. For now, the layers will still be compressed but using the faster gzip from shell.
=> Allow uncompressed layers in container_import

cc/image.bzl, go/image.bzl, java/image.bzl, python/image.bzl
Fixes #201.
I haven't tested how this affects builds inside the rules_docker workspace (as opposed to workspaces that depend on it) as `testing/e2e.sh` started to delete all my local docker images, so I'm relying on CI to test this.
=> Specify repo in references to workspace root

container/bundle.bzl, container/flatten.bzl, container/image.bzl, container/import.bzl, container/push.bzl
Whereas Skylark currently allows dictA + dictB, since Python
interpretation is used for testing Skylark rules, use
dict(dictA.items() + dictB.items()) which will work in both Skylark and
Python. Support for the former is likely going to be removed from
Skylark support at some point.
=> Use Python-friendly dict merging

container/image_test.py, contrib/passwd.bzl, testdata/BUILD
This PR is replacing https://github.com/bazelbuild/rules_docker/pull/190
As per the comments, this PR is removing the tar
=> Remove tar from passwd_file

container/image.bzl
This change should have been included in 
https://github.com/bazelbuild/rules_docker/pull/208
=> use debs param in the _build_layer function

cc/image.bzl, d/image.bzl, go/image.bzl, groovy/image.bzl, java/image.bzl, python/image.bzl, rust/image.bzl, scala/image.bzl
It is currently not possible to reference a language specific image target from another package even with the correct `visibility` set. The cause of this is that the language specific image macros do not pass the visibility attribute to the generated image targets. This PR passes visibility down to the image targets.
=> Apply lang image visibility to underlying image targets.

container/incremental_load.sh.tpl
Removing the unused logic speeds up image loading significantly.
Fixes #200.
=> Remove unused logic from incremental_load script

container/image.bzl
We need to override `tars` attr in addition to `debs` attr.
=> allow override of `tars` for docker_build extensions

java/image.bzl, scala/image.bzl, testdata/BUILD, testdata/Library.scala, testing/e2e.sh
This addresses scala/java interdependencies, and adds support for layering `scala_image`s at a fine grain like `java_image`.
Fixes: https://github.com/bazelbuild/rules_docker/issues/224
=> Scala sandwich testing

container/image.bzl
When interpreting Skylark as Python for testing, comparing the results of `type(foo)` to a string type name doesn’t work. However, using the `type` method on both sides works for both Skylark and Python.
=> Type matching in Python tests

README.md, cc/image.bzl, d/image.bzl, go/image.bzl, rust/image.bzl, testdata/BUILD, testing/e2e.sh
This applies to cc, rust, d, and go (none of which benefit appreciable from layering).
=> Support external binaries in lang_image rules.

README.md
Bumped into #234 while trying rules from git rather than the versioned archive.
Needs a version bump first as the README still points to `v0.3.0` which does not contain https://github.com/bazelbuild/rules_docker/commit/ec4952f1a95f0ccb96fae8829d4aa8d0c9687952.
=> Update passwd example in README.md

WORKSPACE, testdata/BUILD
Pull #235 included the py3_image in the testdata directory, but didn’t use it.
/cc @mattmoor @hwright
=> Use imported py3_image target

cc/cc.bzl, go/go.bzl, java/java.bzl, java/jetty.bzl, python/python.bzl, python3/python3.bzl
Updating the `gcr.io/distroless` DIGESTS via [`./update-deps.sh`](https://github.com/bazelbuild/rules_docker/blob/master/update_deps.sh).
My motivation is to get a version of the python 2.7. with `libssl.so.1.1`. This is present in the latest image but not in the version current specified in DIGESTS. I can update the PR to just include the Python 2.7 DIGESTS changes, if that is preferable.
=> Update gcr.io/distroless digests.

README.md, WORKSPACE, cc/cc.bzl, cc/image.bzl, container/image_test.py, contrib/push-all.bzl, d/image.bzl, go/go.bzl, go/image.bzl, java/image.bzl, java/java.bzl, java/jetty.bzl, lang/image.bzl, nodejs/BUILD, nodejs/image.bzl, nodejs/nodejs.bzl, python/image.bzl, python/python.bzl, python3/image.bzl, python3/python3.bzl, rust/image.bzl, scala/image.bzl, testdata/BUILD, testdata/nodejs_image.js, testdata/package.json, testing/e2e.sh, tools/update_deps.py, update_deps.sh
For now these images are based on gcr.io/google-appengine/base instead of gcr.io/distroless/nodejs for two reasons:
1. The nodejs_binary runfiles includes the node binary, so we need not use a Node.JS base runtime.
1. The generated nodejs_binary entrypoint is currently a bash script, so if/until we can move this logic into our own entrypoint we need a more substantial base runtime.
=> This adds a simple / functional nodejs_image rule.

container/join_layers.py
Use `six` for `iteritems` and ensure config file content is encoded.
=> Make more python3 compatibility improvements

lang/image.bzl
Using binary file path directly instead of guessing with label name.
Fixes #262
I was thinking there should be some more error checking because I access binary [0]. But binary is required so it might be ok. Maybe changing it to `executable=true` or `allow_single_file` would be good? Then it could be accessed using `ctx.files` or `ctx.executables`.
=> Fix go_image not producing a working image

README.md
See https://github.com/bazelbuild/bazel-website/issues/94 for cause of breakage.
=> Fix build icon

container/container.bzl, container/flatten.bzl
puller and importer checksums generated by:
`curl https://storage.googleapis.com/containerregistry-releases/v0.0.24/(puller, importer).par | sha256sum`
=> containerregistry v0.0.23 -> v0.0.24

README.md, container/BUILD, container/image_test.py, contrib/group.bzl, contrib/passwd.bzl, testdata/BUILD
This change adds support for multi-user passwd files in passwd_file rule and implements an analogous rule to build a group file.
Warning: this change will break current users of passwd_file. Please let me know if that's acceptable and whether I need to do anything special.
=> Improved passwd_file rule, new group_file rule

.ci/rules_docker.json
Bazel's CI removed the explicit "docker" VMs and instead Docker is now available on all Linux VMs.
Update the configuration to run all tests on all Linux VMs.
=> Update CI configuration for new Docker support

contrib/group.bzl
This change mirrors what has already been done for passwd.bzl rule in
commit 0d6b0a387b1a04e3b987f9761d21a41b1edc8039.
=> better approach to file output for group.bzl rule

README.md
It looks like this section is about how to authenticate with a docker registry.
Apologies @mattmoor I keep seeing this (and linking to it) and it seemed worth fixing XD
=> Use 'authentication' instead of 'authorization'

container/container.bzl
Fixes: #314
puller and importer checksums generated by:
curl https://storage.googleapis.com/containerregistry-releases/v0.0.25/(puller, importer).par | sha256sum
=> containerregistry v0.0.24 -> v0.0.25

groovy/image.bzl
The layers object is frozen so attempts to modify it will result in a crash.
This will happen if it is called without settint the layer parameter.
```
groovy_image(
name = "hello",
srcs = glob(["Application.groovy"]),
main_class = "example.Application",
)
```
All test cases are currently called with the layer parameter set and thus avoid triggering this behaviour.
Unfortunately, the example in the readme does not have it and is currently failing.
=> Fix groovy_image crash on recent bazel versions

cc/image.bzl, d/image.bzl, go/image.bzl, groovy/image.bzl, java/image.bzl, nodejs/image.bzl, python/image.bzl, python3/image.bzl, rust/image.bzl, scala/image.bzl, testdata/BUILD, testing/e2e.sh
https://github.com/bazelbuild/rules_docker/issues/269
The lang image rules like `go_image` did not propagate tags
through to the `lang_image` rule so one could not use
build_tag_filters correctly (since there was always an
untagged image rule that depended on the binary rule
to be excluded).
=> The lang image rules like go_image did not propagate tags

python3/image.bzl
I think?
`py_debug_image_base` -> `py3_debug_image_base`
=> Fix typo in Python 3 image code

container/bundle.bzl, container/flatten.bzl, container/image.bzl, container/layer.bzl, container/layer_tools.bzl, container/push.bzl
This adds capability to override base and outputs of
_container.image.implementation(ctx, ...) from another rule's
implementation.
=> Expose base and outputs to be overriden.

container/image_test.py
Fixes: https://github.com/bazelbuild/rules_docker/issues/391
Observed delta in Travis is 8 minutes, doubling that should make the build green while still guarding against macroscopic bugs.
=> Increase the allowablebuild time delta to 15 mins

container/container.bzl
Per https://github.com/httplib2/httplib2/pull/91  Which adds the DigiCert Global Root G2 serial to cacert.txt  Without this push_image() fails to registries trusted by the DigiCert CA.  @mattmoor
=> Bump httplib2 library to 0.11.3 for DigiCert

WORKSPACE
- Bazel 0.12.0 release notes say:
The native http_archive rule has been deprecated. Use the Skylark
version available
https://blog.bazel.build/2018/04/11/bazel-0.12.html
- Also upgrade some of the dependencies with their latest releases
=> replace git_repository rule with new http_archive rules

container/incremental_load.sh.tpl, container/push-tag.sh.tpl, container/testenv.sh, contrib/push-all.sh.tpl, contrib/structure-test.sh.tpl, testing/e2e.sh, update_deps.sh
There are still systems widely in use where bash does not exist at /bin/bash (e.g. NixOS), or where /bin/bash is an extremely outdated version of bash (MacOS).  Using /usr/bin/env to find it increases
portability.  It's not hermetic, but /bin/bash was already not hermetic.
=> Use /usr/bin/env bash for more portable shebang lines

WORKSPACE, nodejs/image.bzl
This https://github.com/bazelbuild/rules_nodejs/pull/193/files#diff-09498dbadf45966909850dc8a47ebb13R30 will break this rule when it is released.
This isn't yet released with `rules_nodejs` but will be in the next release.
@gregmagolan just aheads up.
=> Update rules_nodejs to 0.9.1 and fix node target

container/container.bzl
I found an url that gives you trouble at least if you use SSH keys to clone the repositories
=> Add missing .git in subpar remote url

java/image.bzl
The guard against re-importing `javax_servlet_api` must check the actual name
it is guarding against.
=> Fix javax_servlet_api exclusion

container/build_tar.py
This pull request fixes #339 for my specific use case. I tried circumventing this issue by using `BAZEL_PYTHON` but that doesn't work, as it does not seem to respect that.
=> Python 3 build_tar fix

container/container.bzl, container/image.bzl, container/import.bzl, container/layer.bzl, skylib/zip.bzl
This ought to make the gzip and gunzip actions work on systems where the gzip binary is in a path that would not normally show up in the action sandbox.
For example, on NixOS the gzip binary is typically at `/run/current-system/sw/bin/gzip` (or possibly elsewhere if a user has installed it into their own profile).  While these locations are definitely present in `$PATH`, Bazel does not normally make them available in execution sandboxes.
There should be no noticeable difference on any system where these rules were already working; this change broadens support and makes the non-hermetic steps explicit.
=> Make non-hermetic gzip/gunzip more portable

container/container.bzl
Pin to https://github.com/GoogleContainerTools/container-structure-test/commit/7411da1d4cb505f1a70ae5d1ca3d961a3fa66cda. This is required to test any image with an entrypoint other than bash or sh.
=> Move container structure test pin to fix entrypoint.

container/image.bzl, nodejs/image.bzl
The `+` operator on dicts is deprecated and will be removed from Bazel.
=> Remove usages of + on dicts from .bzl files

container/container.bzl
This avoids the INFO: SHA256... build spam with bazel 0.14.0.
Two SHAs already have to be updated when changing
CONTAINERREGISTRY_RELEASE, so adding a third shouldn't be a problem.
=> Add a SHA256 for containerregistry.tar.gz

container/container.bzl
[google/containerregistry v0.0.27](https://github.com/google/containerregistry/releases/tag/v0.0.27) Changeset includes:
* Allow "access_token" in token response.
* Attempt to mount layers from src repo in tools/docker_appender.
* Fix bad error messages involving docker_names with _repr
Fixes #425
(seen working in my project that uses `rules_docker` against ACR)
=> Update containerregistry dependency to v0.0.27

contrib/test.bzl
Include the package name in the new image tag to avoid conflicts on naming
when running multiple container_test on images with the same target name
from different packages.
=> Fix container_test's input image naming conflict.

contrib/BUILD, contrib/compare_ids_test.bzl, contrib/extract_image_id.sh
Also changed the script that had that function to now use the new script instead
(This was done so that the script can be used to replace the more flaky one used in the base-image-docker repo)
=> Made function extract_image_id into its own script

contrib/compare_ids_test.bzl, contrib/compare_ids_test.sh.tpl, contrib/extract_image_id.sh, tests/contrib/BUILD
Passing an invalid tarball into compare_ids_test would give a false
passing test. Added fix for this as well as a message to stderr which clearly
states that there was an issue extracting a manifest.json, and to make
sure the tarball is a valid image tarball.
Also changed compare_ids_test attr 'tars' to 'images' for clarity
(This will break the usage of the rule in our private repo and base-images-docker. I will fix this.)
=>  Fixed bug involving passing in invalid image tarball 

container/build_tar.py, container/image.bzl, contrib/compare_ids_test.bzl, testdata/BUILD, testdata/gen_deb.py, testdata/utils.bzl, tests/docker/BUILD, tests/docker/configs/deb_image_with_dpkgs.yaml
Fixes #386.
When run with Python 3, this will prefer the built-in `lzma` module to extract xz-compressed tarfiles in the `.deb`. Similar to the behavior of `tools.build_defs.pkg.archive` for compatibility with Python 2, this will use `xzcat` (technically with `xz` and specific flags so it behaves as `xzcat`).
I've tested this with `.deb` files with `control.tar.gz` and `control.tar.xz` from stretch and buster, under Python 2.7 and 3.6.
=> Support control.tar with xz or gzip compression

container/container.bzl, tests/docker/configs/test.yaml
This fix the container_test giving false negative test results issue.
For more context, please see
https://github.com/GoogleContainerTools/container-structure-test/issues/146
=> Update structure test pin.

skylib/zip.bzl
Allow client side to override GZIP variable to control the compression speed/ratio.
=> Set use_default_shell_env to True in zip.bzl

README.md
Importing `go_repositories()` appears to be no longer necessary for using the `go_image` rule and, in fact, produces an error.
=> Remove unnecessary imports

container/image_test.py
Two python functions had the same name, so one was overriding the other. Probably a copy/paste error.
=> Changed name of a function

cc/image.bzl, container/image.bzl, container/image_test.py, container/layer_tools.bzl, d/image.bzl, go/image.bzl, groovy/image.bzl, java/image.bzl, lang/image.bzl, nodejs/image.bzl, python/image.bzl, python3/image.bzl, rust/image.bzl, scala/image.bzl, testdata/BUILD, testdata/py3_image.py, testdata/py_image.py
This supersedes #365. And should fix #355, #378, #451
=> Fix workdir and expand arg location.

WORKSPACE, container/container.bzl, contrib/BUILD, contrib/test.bzl
Reverts bazelbuild/rules_docker#456
This PR uses an older version of container_structure_test which will cause regression in container_test rule.
=> Revert "Use container_structure_test release binary for container_test."

WORKSPACE, container/container.bzl, contrib/BUILD, contrib/test.bzl
This reverts commit 7be17569de00477c2fcaae8f0e64371ebcd6fa58 and uses container structure test 1.4.0.
=> Update container_structure_test to 1.4.0 release.

.travis.yml, container/build_tar.py
Recent debian packages from sid can come XZ compressed. This lets you use lzma to build these .debs if it is installed and gives a helpful error message if it isn't.
=> Use lzma to decompress .tar.xz debian files.

contrib/compare_ids_test.bzl
Without this the extract_image_id.py dep was not found in local-docker or remote execution builds
=> fix issue with runfiles for compare ids test

python/BUILD
Create py_runtime rule to use with envs that have python pointing to python2 version
To run a build in an environment that has which python point to a version python3 you need to add the following flag:
--python_top=//python:py_runtime_2
You must also make sure to have a symlink to a valid python 2 binary in "/usr/bin/python2"
Solves:
https://github.com/bazelbuild/rules_docker/issues/454
Replaces:
https://github.com/bazelbuild/rules_docker/pull/481
Note. PYTHON2 IS A DEPENDENCY OF THESE RULES (due to deps of container regsitry). While theoretically it should be possible to refactor container registry to remove this dependency, that is a big refactoring we do not need atm. This PR solves the issue that Bazel by default picks the python binary found with "which python". If which python …
=> Fix builds with python3 as default python

container/flatten.bzl, container/layer_tools.bzl, container/push.bzl, java/image.bzl
replaces https://github.com/bazelbuild/rules_docker/pull/489
=> Remove usages of deprecated Bazel features

README.md, container/BUILD, container/image_test.py, java/image.bzl, lang/image.bzl, testdata/BUILD
https://github.com/bazelbuild/rules_docker/issues/500
- Also adds missing skylib declarations for providers.bz
- also remove unnecessary setting of runfiles tree in java image
=> fix readme to point to 0.5.1

.gitignore
Ignore object files generated by python 2 in the git repo
=> Ignore python 2 compiled bytecode files in git repo

README.md, container/container.bzl, container/image.bzl, tests/docker/BUILD
This PR adds an additional predeclared output to the `container_image` rule which contains image digest of that image.
This PR depends on https://github.com/google/containerregistry/pull/87 and needs to be updated with a version of containerregistry that contains those changes.
Fixes #271.
```bzl
go_binary(
name = "smith",
embed = [":go_default_library"],
pure = "on",
visibility = ["//visibility:public"],
)
container_push(
name = "smith.push_docker",
format = "Docker",
image = ":smith",
registry = ...,
repository = ...,
stamp = True,
tag = ...,
)
```
```console
$ bazel build  --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64  //cmd/smith:container.digest
INFO: Analysed target //cmd/smith:container.digest (0 packages loaded).
INFO: Found 1 target...
Target …
```
=> Image digest output for container_image rule

container/join_layers.py
My default python runtime is python3. When building a container.tar with
`bazel build //container_image:container_image.tar`
following error is thrown
```
File "......../execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/io_bazel_rules_docker/container/join_layers.py", line 113, in uncompressed_blob
return reader.read()
File "/usr/lib64/python3.6/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 1049: invalid start byte
Target //container-images/app-detector:app-detector.tar failed to build
Use --verbose_failures to see the command lines of failed build steps.
```
This PR modifies open arguments in …
=> join_layers read blobs as binary (py3 support)

container/incremental_load.sh.tpl, container/push-tag.sh.tpl, contrib/push-all.sh.tpl, testdata/BUILD, testdata/cc_image_wrapper.sh, testing/e2e.sh
The launcher scripts were not able to find runfiles when executed
deeper inside a runfile tree generated by another rule.  This
happens when another rule depends on the container image target
and wants to execute the scripts from its own runfiles tree.
Fix discovery to also account for this possibility, using similar
heuristics as FindModuleSpace in the python launcher.
=> Fix runfiles discovery

contrib/compare_ids_test.py
Helps update shas for container reproduction tests for to debug them
when run on machines where remote access isn't an option
=> Print digest mismatch on failure in compare_ids_test

cc/cc.bzl, go/go.bzl, java/java.bzl, java/jetty.bzl, nodejs/nodejs.bzl, python/python.bzl, python3/python3.bzl
Make sure we have the changes from GoogleContainerTools/distroless@464d1ef
Fixes #546
=> Run ./update_deps.sh to pull in latest security fixes from distroless.

WORKSPACE, tests/docker/BUILD
Needed as part of bazelbuild/bazel#6283.
=> Update rules_go to 0.16.0

cc/cc.bzl, go/go.bzl, java/java.bzl, java/jetty.bzl, nodejs/nodejs.bzl, python/python.bzl, python3/python3.bzl
This includes the commit https://github.com/GoogleContainerTools/distroless/commit/f93e9b5c88a0ac6b98bc4ff94d206702cfb4e7e3
It adds the full text for various OSS licenses
=> Run update-deps.sh

container/BUILD, container/build_tar.py, container/container.bzl
* This was added in https://github.com/bazelbuild/rules_docker/commit/e9e2809b7099f92e46f9e8336cda041ab78fcf35 to access a feature not available in bazel release, should not be needed anymore
=> remove use of bazel tools from external workspace

toolchains/docker/BUILD
The docker toolchain is only meant to be used in the target platform.
Thus the host environment is irrelevant and the registered toolchains
shouldn't include constraints from those
See https://github.com/bazelbuild/rules_k8s/issues/215 which lead to the discovery of this issue. Specifically https://github.com/bazelbuild/rules_k8s/issues/215#issuecomment-437059049 explains why.
https://github.com/bazelbuild/rules_k8s/pull/218 makes the same fix for rules_k8s
=> Remove exec constraint for docker toolchain

container/image_test.py, tests/docker/java/BUILD, tests/docker/java/configs/BUILD, tests/docker/java/configs/java_image_entrypoint.yaml
lets try to reduce the use of image_test.py for as many use cases as possible now that container_test can do equivalent functionality. The one use case I think we dont support now is finding files by layers, but for almost everything else we should be able to use container_test. This PR is an example so other tests can be migrated or added in the future in a similar way.
=> migrate first java_image tests from image_test.py to container_test

java/image.bzl, testdata/BUILD, testing/e2e.sh, tests/docker/BUILD, tests/docker/configs/java_entrypoint.yaml, tests/docker/configs/java_partial_entrypoint.yaml
Allows additional jvm_flags to be provided at runtime. Example of this in kubernetes would look something like:
```
- name: myapp
image: myapp
args:
- '-Xmx10g'
- '-Xms10g'
- 'com.mycompany.MyApp'
- 'applicationArgument1'
- 'applicationAgument2'
```
Based on some initial discussion here: https://github.com/bazelbuild/rules_docker/issues/548
The intent here is to allow users to build a single image with the java_image rule, but to have the ability to add JVM parameters at runtime based on the context in which they are running the image (size of pod, production vs test environment). This is preferable to having to build an image per combination of possible flags they would require. If there is a better way to supply these flags at runtime I am happy to discuss alternatives.
The idea in the …
=> makes java_image rule main_class parameter optional

testing/e2e.sh
The function NOT CONTAINS would output success if any line in the output did not contain substring.
The new version outputs success if no line in the output contains substring.
Not sure if this was intentional, naming seems to suggest it wasn't.
=> Fix not contains in end-to-end tests

testing/e2e.sh, tests/docker/BUILD
Add a simple test for container_push by starting up a local registry and using that to push the image. We are using a hardcoded port, not sure if that will work on travis. Lets let it run...
fyi @ceason this PR should enable you to test https://github.com/bazelbuild/rules_docker/pull/591 easily
=> add test for container_push

container/BUILD, container/container.bzl, docker/BUILD, skylib/BUILD, toolchains/docker/BUILD
This was deprecated in https://github.com/bazelbuild/bazel-skylib/commit/6e2d7e4a75b8ec0c307cf2ff2ca3d837633413ca
=> bazel_skylib: update reference to @bazel_skylib//:bzl_library.bzl

container/providers.bzl, container/push-tag.sh.tpl, container/push.bzl, tests/docker/BUILD
This PR adds a 'digest' field to PushInfo provider. The field's value is a `<File>` containing the to-be-published image digest.
I rearranged the `container_pusher` implementation function a bit, to emphasize that the digester needs to receive the same arguments as the pusher.
=> Add 'digest' field to PushInfo provider.

.bazelci/presubmit.yml
Mac is having issues pulling the base images, lets reduce the number of things we test on mac, sadly, our mac features might drift.
=> removing lots of mac targets from CI builds

README.md
The debs attribute on container_image only extracts the packages. It
doesn't install them.
=> Update docs in response to #611

lang/image.bzl, tests/docker/nodejs/BUILD, tests/docker/nodejs/configs/BUILD, tests/docker/nodejs/configs/nodejs_image.yaml, tests/docker/nodejs/configs/nodejs_image_no_args.yaml
(and possibly other xx_image targets)
Related to https://github.com/bazelbuild/rules_docker/issues/618
=> Add test to highlight issue related to args with nodejs_image 

README.md, container/bundle.bzl, container/image_test.py, container/push.bzl, testdata/BUILD, testing/e2e.sh, tests/docker/BUILD
This PR deprecates the `stamp` attr for the `container_push` and `container_bundle` rules. Given that the stamp format (ie python format syntax) is mutually exclusive with a valid image name (per the [image specification](https://github.com/moby/moby/blob/master/image/spec/v1.md) `{` and `}` are not valid characters), I believe we can safely infer a user's intent to stamp without a separate 'stamp' attr.
=> Automatically infer stamping for container_{push,bundle}

WORKSPACE, container/container.bzl, container/image.bzl, nodejs/image.bzl
If a symbol should be re-exported, that should be explicit.
Also, update the dependencies to get their recent fixes.
Progress towards #621
=> Do not rely on Bazel transtive loads

docker/docker.bzl
Existing users rely on those, so we should provide them explicitly.
=> Explicitly re-export functions in docker.bzl

container/build_tar.py, container/layer.bzl, tests/docker/BUILD, tests/docker/configs/special_characters.yaml
Equals sign is a valid character in paths, so it should not be used
as a delimiter when passing file map to build_tar.py.  For example,
pyspark python package contains directories like 'cls=kittens'
(see https://github.com/apache/spark/tree/master/data/mllib/images/partitioned).
Pass contents as a json manifest file to build_tar.py to resolve the
issue.
=> Support '=' character in path names

container/layer_tools.bzl
`incremental_load.sh.tpl` was updated in bazelbuild/rules_docker#559 to use the path from the toolchain, but there was a `docker run` being dynamically added in `incremental_load()` when `run` was `True`.
=> Use docker path from toolchain in incremental loader

container/build_tar.py, tests/docker/BUILD, tests/docker/apple.bzl, tests/docker/configs/stripped_directory_name.yaml
There is a tiny bug in pkg_tar's strip_prefix handling that prevents it
from stripping the full name of a file. Though this sounds weird at
first, it is pretty useful when creating tarballs from output
directories. A pull request for this has been sent to Bazel:
https://github.com/bazelbuild/bazel/pull/6980
The same issue applies to container_layer's data_path argument, which is
actually where we noticed this at first. Also apply this fix here.
=> Allow container_layer's data_path to work on directory output target names

container/BUILD, container/image_test.py, testdata/BUILD, testdata/stamp_info.bzl
image_test.py currently uses the environment variable USER to obtain the
build user. While this matches the BUILD_USER when bazel is invoked
localy, it can be different when the test action is executed in a remote
machine. This commit makes the Bazel stamp variables available to
image_test.py so that it can obtain the BUILD_USER as set by Bazel.
=> Make obtainer build user in tests remote execution compatible

contrib/structure-test.sh.tpl, contrib/test.bzl
When using the docker driver to run container_tests, use the
fast incremental loader instead of "docker loading" the tarball.
Producing the tarball can be very expensive for large images.
Also rewrite container_test runfiles assembly to avoid calls to
depset.to_list().
=> Use incremental loader in container_test

container/build_tar.py, container/layer.bzl, toolchains/docker/BUILD.tpl, toolchains/docker/toolchain.bzl
The `xz` tool may be used in `build_tar.py` when Python 2 is used (which does not have a built-in `lzma` module) and `backports.lzma` is not installed. Bazel 0.21 flipped the default of `--incompatible_strict_action_env` to true, which means `which xz` is unlikely to work. This can be done in the repository rule to autoconfigure the docker toolchain.
I don't totally love that this is in the _docker_ toolchain, but it felt too heavyweight to separate it into its own, since other users of this toolchain can just ignore the new field.
=> Set path to xz in toolchain when possible

container/BUILD, container/image_test.py, lang/image.bzl, testdata/BUILD, testdata/utils.bzl
Include any symlinks in *_image layers that were added to dependent
runfiles with ctx.runfiles(symlinks=...).
The new feature only works for bazel >= 0.21.0 which has
https://github.com/bazelbuild/bazel/issues/3880 fixed, and for older
versions such symlinks will silently be dropped (like today).
=> Include custom runfile symlinks in layers

container/pull.bzl
I may have introduced a small bug in #544:
```
INFO: Rule 'debian-base-arm' modified arguments {"digest": "sha256:27c1633c98e29cc9ae40b7b50f84a247ff1e50c1804389fec9d570bda359cbbb"} and dropped ["name"]
INFO: Rule 'go_image_base' dropped arguments ["name"]
INFO: Rule 'alpine-base' dropped arguments ["name"]
INFO: Rule 'git-base' dropped arguments ["name"]
```
I'm explicitly setting the name here to make that info message go away. (Note that it seems like everything is still working, so this probably isn't a critical urgent fix.)
=> container_pull: don't drop name in returned arguments

.bazelci/presubmit.yml
The incompatible change process is a little bit more involved than using `--all_incompatible_changes`. We allow creating new incompatible flags which we don't expect users to migrate for right away. The principled place to look for incompatible changes is to go to https://github.com/bazelbuild/bazel/issues?q=is%3Aissue+label%3Aincompatible-change+label%3Amigration-ready, ideally also filtered with the bazel version (e.g. for flags that should be migrated in bazel 0.22.0, add the label 'migration-0.22'.
On the buildkite, this is the pipeline that tells rule owners which incompatible flags they have to migrate for in the current bazel release: https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags
This PR fixed the failure on the Bazel downstream pipeline: …
=> Do not add --all_incompatible_changes to presubmit

container/incremental_load.sh.tpl
We are running into some smaller issues, where we want to run the binary output of the x_image rules in another script, but then when this script wants to gracefully terminate all its child processes it only kills the bash process but not the docker run it executed. As far as I can tell (and from testing) the `cleanup` function does not do anything in this case so it should also be no problem that it is not getting called anymore.
And in general I think it is nicer in a case like this, where we have a wrapper script that just sets up a few things before executing a single binary that this binary then becomes the main process.
=> exec docker run statement.

go/image.bzl
I'm trying to build a go_image with a go_binary marked as restricted_to=[... some environment...] and it fails, apparently because app_layer() doesn't see the restricted_to values passed to go_image. This also passes through compatible_with for good measure.
=> go_image() now respects restricted_to and compatible_with

README.md
When I tried using it, `bazel` says it is depreated.
`DEBUG: /.../home/chanseok/.cache/bazel/_bazel_chanseok/2fa25e6c02293c6f4b6133cec26037eb/external/io_bazel_rules_docker/container/bundle.bzl:42:9: Attr 'stamp' is deprecated; it is now automatically inferred. Please remove it from //:all`
=> Update container_bundle doc to remark deprecation of "stamp" attribute

container/BUILD, container/build_tar.py, container/image_test.py, repositories/repositories.bzl, tests/docker/BUILD
Replaces https://github.com/bazelbuild/rules_docker/pull/694 
* adds import of bazel at commit at which mtime was added
=> Set default_mtime=0 on TarFileWriter so that elements default to the epoch

repositories/repositories.bzl
container-structure-test 1.7.0 adds the ability to test image metadata with regexs.
_Updated to container-structure-test v1.8.0, which pulls in the 0-byte layer.tar fix from 
google/go-containerregistry_
=> Update to container-structure-test 1.8.0

container/BUILD, contrib/BUILD, tools/BUILD
This moves the `py_binary` rules to use the internally downloaded `@six` dependency, rather than the one from `@bazel_tools`. Previously, both versions of six were in the runfiles, causing odd issues when the incorrect one was resolved first when six was imported.
Additionally, to fix the `__init__.py` issue, this also toggles `legacy_create_init`, which has been done for all targets that support it. The `//container:build_tar` target is the only one that still needs this enabled, due to the dependency on `@bazel_source` that appears temporary.
Alternatively, the internally downloaded six could be removed and you could depend on the `@bazel_tools` one.
=> Use internally downloaded @six and disable legacy_create_init

container/push.bzl, testing/e2e.sh, tests/docker/BUILD
I need ability to specify tag of image for push as content of file.
I added `tag_file` attribute to `container_push` rule.
=> container_push: added attribute 'tag_file'

.bazelci/presubmit.yml, cc/image.bzl, container/BUILD, container/image.bzl, container/layer_tools.bzl, contrib/BUILD, contrib/rename_image.bzl, d/image.bzl, go/image.bzl, groovy/image.bzl, java/image.bzl, lang/image.bzl, nodejs/image.bzl, python/image.bzl, python3/image.bzl, rust/image.bzl, scala/image.bzl, tests/docker/BUILD, tools/BUILD
Still get
./container/image.bzl:342: uninitialized: Variable "layer" may not have been initialized. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#uninitialized)
which seems to be a bug in buildifier because the loop variable in a
list comprehension is being reported as potentially uninitialized.
Fixes involve adding function, argument, return statement and module
docs.
=> Fix buildifier 0.22.0 warnings in files matching *image.bzl

lang/image.bzl
In upcoming Bazel 0.23.0, the legacy `py` provider [has been changed to `PyInfo`](https://github.com/bazelbuild/bazel/issues/7298), with both being allowed to work currently. However, in a future release the use of `py` will be not be permitted, which can be simulated with `--incompatible_disallow_legacy_py_provider`.
This change forwards the old `py` provider in `filter_layer` in older Bazel, and `PyInfo` in newer Bazel and has been tested to work correctly when `--incompatible_disallow_legacy_py_provider` is enabled. Prior to this change, `filter_layer` would fail when run in this mode.
=> Forward new provider for python in filter_layer

container/pull.bzl, tests/docker/BUILD
The container_build rules publish "foo.digest" for a container "foo".
container_pull names the container "image" and only publishes "digest",
not "image.digest", so far.
=> Publish an image.digest file for container_pull.

repositories/repositories.bzl
This updates the declared version of the subpar dependency to 0356bef3fbbabec5f0e196ecfacdeb6db62d48c0, which includes changes to work with --incompatible_remove_old_python_version_api in Bazel 0.23.
I also sent google/containerregistry#146 to update containerregistry for the same issue. Once that's merged you may wish to update your dependency on them, but I believe the definition I updated in this PR takes precedence anyway.
=> Update subpar dependency

README.md
To address confusion in #690.
Prefer using the `--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64` flag over `goos`, `goarch` and `pure` attrs for `go_image` targets as recommended by go_binary docs [here](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#attributes-2) and [here](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#note-on-goos-and-goarch-attributes).
=> Go image doc update

WORKSPACE
The intention is to get renovate to start picking this up
=> Use a single url in the "urls" field for bazel-toolchains

WORKSPACE, container/pull.bzl, tests/docker/BUILD
To address confusion in #714 when pinning to a manifest list image type.
This forces the user to only pin to a manifest type when using digest.
=> Fail when pulled image with unexpected sha256

container/incremental_load.sh.tpl
Right now, when `docker` is not found through the default-configured toolchain, the error message ends up being quite opaque:
```my/target: line 202: : command not found```
=> Add error message when docker is not available in incremental loader

.bazelci/presubmit.yml, WORKSPACE, contrib/Dockerfile, contrib/dockerfile_build.bzl, docker/dockerfile_build.bzl, testing/e2e.sh, tests/docker/BUILD, tests/docker/configs/basic_dockerfile.yaml
Repo rule that uses the docker binary installed in the system to build a docker image from a given Dockerfile. It then saves that image as a tar file.
=> Repo rule to build an image from Dockerfile and save as tar

.gitignore, container/image_test.py, contrib/passwd.bzl, testdata/BUILD
This will be useful to create an entry like `nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin`.
I'm new to Starlark, so I need some help actually.
=> Allow passwd entry with non-existing home path

container/bundle.bzl, container/flatten.bzl, container/image.bzl, container/import.bzl, container/layer.bzl, container/layer_tools.bzl, container/push.bzl, contrib/push-all.bzl, lang/image.bzl
This addresses the incompatible change via the ----incompatible_disallow_struct_provider_syntax flag described [here](https://github.com/bazelbuild/bazel/issues/7347).
=> Return providers instead of struct from rule impl functions

README.md, container/image.bzl, testdata/BUILD
Fixes #728, #739 
Closes #584
Related to #505, #482
=> `legacy_run_behavior` value shouldn't be taken from base.

container/incremental_load.sh.tpl
When #667 was merged, the assumption was that the cleanup handler does not do anything -- but we've since seen a lot of files left around in /tmp on our CI machines from this change.
Since we've already loaded the layers into the docker daemon before `docker run`ing, we can run the cleanup before we `exec docker`.
As an aside...
I'm slightly hesitant that the cleanup step could take a while, which means we're making the race condition from `docker tag` and a much-delayed `docker run` worse.
Maybe the `tag_reference` in the built `run_statements` should use `tag@sha256:digest` format, since we _do_ have the digest available?
=> Add cleanup before docker run in incremental loader

container/push.bzl
internally, we need to pass a single stamp-info-file arg with comma
separated values. This change has no effect externally, but will
make copybara transformation work
=> modify how stamp-info-file is calculated

.bazelci/presubmit.yml, .bazelignore, .bazelrc, README.md, WORKSPACE, python/BUILD, python/image.bzl, python3/image.bzl, toolchains/python/BUILD
Changes required for use upcoming python toolchains features:
* create a `py_runtime_pair` and toolchain that is compatible with the base containers used in `py_image` and `py3_image`
* register toolchains in `deps` targets for `py_image` and `py3_image`
* Set explicitly `python_version` in `native.py_binary` calls in image.bzl for py and py3
* Adds flags to `.bazelrc` so all our CI runs with testing these fatures
Note: flags that will only work with 0.25.0. But I tested that changes are still OK on CI if flags in bazelrc are not turned on.
* Update readme to document use of python toolchains
* extra: Use .bazelignore to avoid building anything under testing/examples/
=> test use of incompatible_use_python_toolchains flag with Bazel 0.25.0

contrib/test.bzl
The argument of string.join should be a list of strings. In the future,
Bazel won't perform this implicit conversion.
=> Fix for Bazel upcoming change incompatible_string_join_requires_strings

contrib/test.bzl
Tie _container_test_'s `verbose` attribute to _container-structure-test_'s `--verbosity` flag.
Fixes #863 
cc: @nkubala
=> container_test verbose should drive verbosity

container/incremental_load.sh.tpl, container/layer_tools.bzl
This fixes the bug mentioned in #793. When we don't generate any run statements (that is, `run` in `incremental_load()` is false), we don't `exec docker`, and the cleanup runs twice.
=> Fix incremental loader cleanup when no run statements are defined

WORKSPACE, container/go/cmd/puller/BUILD, container/go/cmd/puller/puller.go
Added function `pull` that pulls an image in go.
The function reuses the implementation of `crane pull` [here](https://github.com/google/go-containerregistry/blob/15879f261e2082fe64b9f92d6738f4d959615dfc/pkg/crane/pull.go#L51) with additional platform specification feature.
=> Add puller function in go

.travis.yml, container/pull.bzl, testdata/BUILD, testing/e2e.sh
Bazel 0.27.0 can no longer run on Trusty machines.
=> Update travis to use xenial test base.

java/image.bzl, lang/image.bzl, nodejs/image.bzl
Besides exposing the rule itself, it is a common pattern to expose
rule attributes, outputs, toolchains and the implementation function
as a struct.  This makes it easier to wrap the rule in another rule,
without duplicating the attribute definitions.  Apply this pattern
to lang/image.bzl, and remove duplicated definitions from the wrapping
rules in java/image.bzl and nodejs/image.bzl.
=> Expose attributes from lang/image.bzl as struct

container/go/cmd/puller/BUILD, container/go/cmd/puller/puller.go, container/go/pkg/oci/BUILD, container/go/pkg/oci/write.go
Extended rules_docker API to now contain the `Write` function which outputs the images from the puller in OCI standard format. BUILD files updated in the process.
=> Implement OCI image puller binary and writer utility

.bazelci/presubmit.yml, WORKSPACE, container/new_pull.bzl, repositories/repositories.bzl, tests/docker/BUILD
Modified the starlark (`.bzl`) rules to account for the new puller binary being uploaded to the cloud.
Old puller is left intact, invoke `new_container_pull` to use new puller.
Current speculative container_import written to BUILD file in output directory, see comments for details. No compatibility issues with container_import as of now (??) but potentially will need to refactor puller.go to allow reader to ingest such pulled data.
=> Create new starlark rules for new_container_pull

README.md
The documentation currently doesn't provide any details about how the `war_image` macro works internally. Only by trying did I find out that the web application is served by a Jetty Servlet container. Users will also need to understand that you cannot use a `web.xml` but have to declare annotations instead for Servlets to be discovered.
As a side note: As an end user I do not find the name of the macro very fitting. `war_image` somewhat implies that a WAR file is built but that's not the case. Maybe `java_web_image` would be a better name.
=> Clarify end user details for war_image macro

WORKSPACE, container/new_load.bzl, repositories/repositories.bzl, tests/docker/BUILD
Starlark rule to work in accordance with the new loader.go binary.
Note: build currently failing because new loader.go binary is not uploaded.
=> Add new Starlark container load rule new_load.bzl

lang/BUILD
Stardoc currently requires all dependencies to also have a bzl_library, and it seems lang/image.bzl got missed when the rest of the repo has them, from what I can tell.
=> Add bzl_library for lang/image.bzl

container/go/cmd/puller/BUILD, container/go/cmd/puller/puller.go, container/go/pkg/compat/BUILD, container/go/pkg/compat/ociToLegacy.go
For compatibility with the current `container_import` rule, modifies the puller to generate symbolic links to the layers (named `0-n.tar.gz`) and the config as `config.json`.
=> Add symlink to puller's OCI intermediate format

container/go/cmd/puller/puller.go
Noticed that container_import outputs a tarball based on the target name in the container_import target of the pulled image directory's BUILD file. In order to prevent conflicts with such generated files, (i.e. when something like `bazel build @<target_name>//image:<container_import target name>.tar` is run), we simplify the logic of the puller binary.
=> Refactor puller binary to be compatible with container_import

.bazelci/presubmit.yml, WORKSPACE, docker/security/BUILD, docker/security/security_check.bzl, docker/security/security_check.py, docker/security/security_check_whitelist.json, repositories/requirements-pip.txt, tests/docker/security/BUILD, tests/docker/security/cloudbuild.yaml
Continuing migration of all rules needed to build deterministic base containers to rules_docker repo.
This PR migrates a security_check that is still EXPERIMENTAL.
Security check requires gcloud to properly run.
This PR is only migrating existing code, will improve documentation (particularly as related to requirements and expectations of the checker) in upcoming PR
NOTE: PR is not yet passing CI, will need to resolve issue related to permissions and re-run.
=> migrating security check to rules_docker

docker/security/security_check.py, tests/docker/security/BUILD
Was doing a careful line by line diff of the internal & external version
of this script and discovered the following issues:
1. Accidental debug code checked in that disabled checking
vulnerabilities in the base image of a given image.
2. The vulnerability severity being reported in the output YAML was
wrong. effectiveSeverity which was being reported != what the rest of
the script intends to report.
=> Fix a couple of issues that made new security_check different

container/bundle.bzl
according to https://github.com/bazelbuild/bazel/issues/7977
Naive attempt to fix https://github.com/bazelbuild/rules_docker/issues/987
=> Adjust to OutputGroupInfo

container/go/cmd/puller/puller.go, container/go/pkg/compat/BUILD, container/go/pkg/compat/ociToLegacy.go
Added manifest.json symlink to fully parallel the legacy format.
=> Refactor new_container_pull to generate fully backward compatible format

nodejs/image.bzl
The layers never really worked properly as all the nodejs_binary runfiles, including node_modules and the nodejs binary, where still being put into the top-layer anyway. Now that rules_nodejs are supporting toolchain we could fix that partially by also requiring the toolchain, but that would still not fix node_modules. For that we would need a provider from nodejs_binary, which is proposed here: https://github.com/bazelbuild/rules_nodejs/pull/863
So we should fix the layering once it is really possible from the rules_nodejs side.
cc @gregmagolan
=> Remove required node_modules arg and layers

docker/util/README.md, docker/util/commit.sh.tpl, docker/util/run.bzl, tests/docker/util/BUILD
rules_docker _container_run_and_commit_ rule doesn't allow to provide
custom flags to the `docker run` command. custom flags are needed
e.g. setting up container network or dns servers. the
_container_run_and_extract_ rule supports custom setting
_docker_run_flags_ already. this commit adds the missing argument
and same behavior to the _containr_run_and_commit_ rule.
Issue #1026
=> docker/util: adding arg docker_run_flags to container_run_and_commit

WORKSPACE, repositories/py_repositories.bzl, repositories/repositories.bzl
Addresses [renaming canonical workspace issue](https://github.com/bazelbuild/rules_python/issues/203) and fixes #1029
=> Fix rules_python workspace name

container/new_push.bzl
Changed pusher default format to legacy
- Consider changing this back once `container_image` supports oci format.
- Left puller default format to "oci" since puller pulls into two formats by default.
=> Changed pusher default format to legacy

repositories/repositories.bzl
see https://github.com/bazelbuild/bazel-gazelle/issues/609 for why an empty build file is added to testing/examples.
Supersedes https://github.com/bazelbuild/rules_docker/pull/1013
=> upgrade gazelle and fix issue with one of the samples

docker/package_managers/download_pkgs.bzl, docker/package_managers/install_pkgs.bzl, docker/util/run.bzl
Porting from https://github.com/GoogleContainerTools/base-images-docker/pull/366
From that change:
If you are not running docker locally, you need to set some
environment variables to be able to access the docker host.
These environment variables are DOCKER_MACHINE_NAME, DOCKER_CERT_PATH,
DOCKER_TLS_VERIFY & DOCKER_HOST.
Bazel does not pass environment variables to all actions by
default. You need to set use_default_shell_env. This patch enables
this option for docker actions so that a remote docker node can be
used (like is done with CircleCI).
=> Use the default shell for docker commands

.bazelci/presubmit.yml, tests/contrib/BUILD, tests/contrib/repro_imgs.yaml
This test fails sometimes, because in some cases installing the `openjdk-8-jdk` apt package is deterministic.
=> Remove java pkg non-determinism test

container/image.bzl, contrib/repro_test.bzl, docker/package_managers/apt_key.bzl
The escape sequence \s doesn't exist. The current behavior of Starlark
is to insert both `\` and `s` in the string. However, it can be
confusing and not future-proof: backslashes need to be escaped.
Bazel will require it in the future (see
--incompatible_restrict_string_escapes).
=> Escape backslashes in Starlark code

container/image.bzl, container/push.bzl, tests/container/BUILD
Reverted changes in `container_push` and `container_image` to use new digester in go. 
- The digest differs since  `container_push` and `container_image` still rely on manifest created in python containerregistry, which results in a difference in the uploaded manifest and the manifest in `digester.go` used to compute sha256 sum. 
- Resolves issue #1051
=> Revert digester deps for container_push and container_image 

container/go/cmd/digester/BUILD, container/go/cmd/digester/digester.go, container/go/cmd/puller/puller.go, container/go/pkg/compat/ociToLegacy.go
Updated new puller binary `puller.go` to generate digest file to `image/digest`.
=> Updated new puller binary to generate digest file

container/go/cmd/create_image_config/BUILD, container/go/cmd/create_image_config/createImageConfig.go, container/go/pkg/compat/BUILD, container/go/pkg/compat/overrideConfig.go
* Implement `createImageConfig.go` to write out modified config file and empty/base manifest file, maintaining parity with the current behaviour
* Implement an `overrideConfig.go` binary to mutate the base config file to match the updates supplied in the flags. This also contains the `Stamp` utility function that the digester is dependent on.
=> Implement createImageConfig for use in container_image targets

container/image.bzl
* Modify `image.bzl` to accept Golang flags
Note: the image_test.py will fail when using the new Go createImageConfig binary until the sha256 sums are updated to reflect these new changes. See https://github.com/bazelbuild/rules_docker/pull/1024 for how to update the tests accordingly.
=> Update image.bzl to optionally utilize new createImageConfig Go binary

README.md, container/new_pull.bzl
Essentially same API as `container_pull` with the added options for pull format and implicit outputs appended.
=> Add documentation for new_container_pull

README.md
Add the Container Image Promoter project to the list of adopters.
Technically the promoter is not a "company" but it certainly uses rules_docker.
=> README.md: add the K8s Container Image Promoter to adopters

toolchains/docker/BUILD
Enables use of xz_path in cases in which toolchain is not created via workspace rule.
=> Add xz_path to default toolchain

toolchains/docker/BUILD
DO NOT REVIEW YET.
Just need to have CI run on this again
This PR Reverts bazelbuild/rules_docker#1086, which in turn reverts https://github.com/bazelbuild/rules_docker/pull/1084
=> Add (again) xz_path to default toolchain"

toolchains/docker/BUILD
ugh, having to revert again
Reverts bazelbuild/rules_docker#1088
=> Revert "Add (again) xz_path to default toolchain""

WORKSPACE, testing/download_pkgs_at_root/WORKSPACE
Supersedes https://github.com/bazelbuild/rules_docker/pull/1150
We need to update pin to base-images-docker after https://github.com/GoogleContainerTools/base-images-docker/commit/36456edd3cc5a4d17852439cdcb038022cd912e5 as prior has a dep on bazel-toolchains that is no longer valid.
=> update pin to base images docker and bazel-toolchains

README.md
Bazel's `bazelrc` configuration files apply inheritance to *`command`* options. `test` and `run` inherit from `build` so they're no necessary to list I don't think. 
**Ref:** https://docs.bazel.build/versions/master/guide.html#option-defaults
=> Update README.md to remove unnecessary part of instruction.

container/go/cmd/join_layers/BUILD, container/go/cmd/join_layers/join_layers.go, container/go/pkg/compat/BUILD, container/go/pkg/compat/image.go, repositories/go_repositories.bzl
Pulled in new go-containerregistry version that adds ability to generate
v1 image tarballs & add Size method to legacyImage because v1.Image in
go-containerregistry now requires it.
=> Generate v1 image tarballs in Go join_layers

docker/util/to_json.py
Python3 is preferred for running bazel, but somehow some code was committed using incompatible code.
=> fix json print command for py3

WORKSPACE, python/image.bzl, python3/image.bzl, toolchains/py_toolchains.bzl
Changes to python toolchains in these rules caused breakage with Bazel head: https://github.com/bazelbuild/rules_docker/commit/b5e5506d2e2c82a21f9db69ee00e3333f8377e48#commitcomment-35386395
This PR registers an cc_toolchain explicitly for local execution. This is not needed with bazel 0.29.1, but apparently it is needed with Bazel head. Registered cc_toolchain must be compatible with local cc config, so doing a bit of the repo rule dance to get that correctly.
Lets run CI for testing, though Windows will be left uncovered.
=> fix rules_docker with bazel head

container/go/pkg/compat/config.go, tests/container/BUILD, tests/container/configs/set_env_equals.yaml
Taking over https://github.com/bazelbuild/rules_docker/pull/1192 to add tests as we have already had 3 requests this week for this feature:
https://github.com/bazelbuild/rules_docker/issues/1199
https://github.com/bazelbuild/rules_docker/pull/1196
(and https://github.com/bazelbuild/rules_docker/pull/1192)
=> Support env vars that contain '='

WORKSPACE, docker/package_managers/download_pkgs.bzl, docker/package_managers/run_download.sh.tpl, python/image.bzl, python3/image.bzl
We were improperly calling the python script to extract image id from the produced executable.
Also update rule to use providers in return.
=> Fixes for python use in download_pkgs

WORKSPACE, testing/download_pkgs_at_root/WORKSPACE
supersedes https://github.com/bazelbuild/rules_docker/pull/1235
=> update bazel-toolchains and fix reference to exec_propertiers:

python3/image.bzl
Fixes issue https://github.com/bazelbuild/rules_docker/issues/897
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bazelbuild/rules_docker/1244)
=> Fix pip in py3_image

repositories/repositories.bzl
In late September, rules_go's maintainers started tagging their releases vX.Y.Z rather than X.Y.Z - https://github.com/bazelbuild/rules_go/releases/tag/v0.20.1 for example. The Google mirror has the correct URL, but not the GitHub one.
=> Fix rules_go mirror URL

docker/package_managers/install_pkgs.bzl, docker/util/BUILD, docker/util/image_util.sh.tpl, docker/util/run.bzl
"image_util.sh" does not respect the docker toolchain.
this PR generates "image_util.sh" from a template instead.
=> Dont assume docker path in image util

README.md, container/image.bzl, container/import.bzl, container/layer.bzl, repositories/repositories.bzl, skylib/zip.bzl, testing/default_toolchain/WORKSPACE, testing/default_toolchain/local_tool.bzl, testing/java_image/BUILD, testing/java_image/Gzip.java, testing/java_image/WORKSPACE, toolchains/docker/BUILD.tpl, toolchains/docker/toolchain.bzl
local_tool is problematic as it does not work with remote execution.
Gzip, like other tools we use in these rules, should be part of the docker toolchain. This PR removes code related to using local_tool (moves it to a test, as use case is still valid) and moves gzip to the docker_toolchain. Also added tests in java_image to use a java based gzip target.
=> define gzip in the docker toolchain not as a local tool

docker/util/config_stripper.py
Previously, config_stripper would store the full
TAR file and gzipped TAR file in memory to compute
the SHA256 hash.
After this change, the stripped TAR file is stored
in a temporary location on disk and then renamed
into its final location.  Furthermore, the SHA256
hash of the gzipped TAR file is computed
incrementally as the gzipping progresses.
=> config_stripper no longer stores full file in RAM.

WORKSPACE
As of the newest version of bazel-toolchains, merge_dicts is deprecated.
This PR updates to that version and migrates away from merge_dicts in anticipation for a breakage that would have happened on the next upgrade.
=> Replace merge_dicts with dicts.add

container/go/pkg/compat/config.go, container/go/pkg/compat/config_test.go
The entrypoint prefix is appended to the entrypoint but should be
prepended
=> Fix ordering of docker entrypoint and entrypoint prefix

WORKSPACE
The current rules_groovy uses `maven_server`, which has been removed in Bazel 2.0.
=> Update rules_groovy to prepare for Bazel 2.0

container/push.bzl
I noticed that the digest field was removed in https://github.com/bazelbuild/rules_docker/pull/1142 . Our internal rules were depending on this field. Can it be added back?
=> Add digest field back to to PushInfo

container/push.bzl, contrib/push-all.bzl
The robot_email attr is used at Google internally and github users should not be using it.
=> Add robot_email attr to container push bzl rules

container/BUILD, contrib/BUILD, testdata/BUILD, testing/e2e.sh, tests/container/BUILD
I made this change in an internal fork of this repo that I help maintain for my job, but figured it might be useful upstream as well considering the approaching deprecation of Python 2. This _shouldn't_ cause any issues with containers being able to run Python 2 still as far as I can tell, it just changes tools to run in Python 3 and removes any instances of the `--host_force_python=PY2"` option.
If for some reason this shouldn't be merged right now (or at all) please let me know.
=> Change to using python 3 in host configuration

container/BUILD, contrib/BUILD, testdata/BUILD, testing/e2e.sh, tests/container/BUILD
Reverts bazelbuild/rules_docker#1318
Breaks internal tests because internally we depend on some libraries that haven't been migrated to PY3. In order to use PY3, we'll have to migrate to using absl.flags instead of gflags.
=> Revert "Change to using python 3 in host configuration"

container/go/cmd/puller/puller.go
Configure the HTTP transport used by the container puller tool to
recognise the standard http_proxy/https_proxy/no_proxy environment
variables.
If these variables are present in the host environment, Bazel sets them
in repository rule contexts by default.
Fixes #1241
=> Add http(s)_proxy env var support to puller

WORKSPACE
replaces https://github.com/bazelbuild/rules_docker/pull/1337
=> update rules_groovy call to repositories.bzl

WORKSPACE, java/image.bzl
Fixes https://github.com/bazelbuild/rules_docker/issues/1373, subsumes https://github.com/bazelbuild/rules_docker/pull/1374, also adding change to update pin to rules_scala. But in order for anything to pass CI now, we need to also update our references to maven central.
=> update rules scala to pick up maven to https change

container/go/pkg/compat/image.go, repositories/go_repositories.bzl
Take advantage of
https://github.com/google/go-containerregistry/pull/655 and avoid
loading an uncompressed layer into memory when writing out an image
tarball.
This fixes #1349
=> Implement UncompressedSize to take advantage of memory opt

README.md, WORKSPACE, container/BUILD, container/image_test.py, nodejs/image.bzl, testdata/BUILD, testdata/nodejs_image.js, testdata/nodejs_image_lib.ts, testdata/package.json, testdata/yarn.lock, tests/container/nodejs/BUILD
Adds support for `NodeRuntimeDepsInfo` and `NpmPackageInfo`
This ensures that npm deps are placed in their own layer, improving caching and rebuilds
Also puts nodejs and nodejs args so that it can be cached between instances of nodejs_image targets.
based off work started here https://github.com/bazelbuild/rules_docker/pull/487/files
=> add layer for npm packages

toolchains/docker/toolchain.bzl
`toolchain_configure` uses `repository_ctx.which`, and saves the result into the external repository's generated `BUILD` file, so it has to be rerun if `PATH` changes.
=> Declare PATH environment variable as a dependency.

README.md, container/go/cmd/create_image_config/create_image_config.go, container/go/pkg/compat/config.go, container/image.bzl, repositories/go_repositories.bzl, testing/e2e.sh
Fixes #1429
Just tested this manually and it seems to work!
I'm mostly just interested in getting os.version to plumb through bazel from the intermediate form config file, which is fixed by just bumping the dependency on go-containerregistry to pick up https://github.com/google/go-containerregistry/pull/676, but it seems like a reasonable thing to also expose in the rules.
I can remove the rules changes and just update the dependency if this feels unnecessary, but exposing this just feels more "complete", y'know? Let me know what you think.
=> Plumb os.version through container image config files.

WORKSPACE, tests/container/cloudbuild.yaml
After Bazel container was updated to include Clang 11.0.0, this GCB test
started to fail because the toolchain config it uses is pinned to an
older Bazel container but the Bazel container the test runs in uses
"latest". From what I can tell, the test is meant to ensure RBE supports
the exec properties that enable sibling docker so I don't think we're
losing test coverage.
=> Fix CI failures due to Clang 10 -> 11 upgrade

nodejs/image.bzl
We were getting `data` from `kwargs`, but it will always be `None` since we declare an explicit `data` in the function parameters. This only passes the `data` function parameter to the `app_layer` data.
This fix is required for using arguments on the `nodejs_image`, e.g.:
```starlark
nodejs_image(
name = "my_image",
binary = ":my_bin",
args = ["$(rootpath config.json)"],
data = ["config.json"],
)
```
=> Fixed passing data to app_layer in nodejs_image

README.md
This PR was triggered by https://github.com/bazelbuild/rules_docker/issues/1448 to make it clear that the behavior may differ between using `""` and `[]` for `cmd` and `entrypoint` when using `container_image`-rule.
=> docs(container image): add info for cmd and entrypoint regarding "" & []

java/image.bzl
another depset. Passing a depset as first argument to the depset
constructor is deprecated.
This fixes #1344 (and duplicate #1333).
=> java_files() already returns a depset, don't wrap the return value in

README.md, container/BUILD, container/build_tar.py, repositories/repositories.bzl, testdata/BUILD, tests/docker/toolchain_container/BUILD
This repository is currently using a deprecated version of Bazel's package management code. This PR updates all references to `@bazel_tools//tools/build_defs/pkg` so that they instead use `@rules_pkg//`, which is maintained.
Note: this PR does not replace `rules_docker`'s custom version of `build_tar.py` with the one contained in `rules_pkg`. It should not result in any changed behavior at all.
=> Use rules_pkg repository instead of deprecated pkg files

container/BUILD, testdata/extras_gen.py
Also configure build_tar binary to use Python 3.
=> Update one remaining reference to deprecated rules pkg

container/build_tar.py, container/image_test.py, repositories/repositories.bzl, tests/container/BUILD
Resolves https://github.com/bazelbuild/rules_docker/issues/633
This PR also includes:
- Updates to test fixture sha256 values (which are different because of the mtime processing change).
- An update to the latest release of the rules_pkg repository.
=> Enable mtime preservation in tar file building process

container/BUILD, container/build_tar.py, container/image_test.py, testdata/BUILD
This fixes a mistake in https://github.com/bazelbuild/rules_docker/pull/1489 - I missed one instance of hardcoding the value False. This PR also adds a test of this configuration option.
=> Correctly read users' enable_mtime_preservation config

WORKSPACE
The Bazel GPG key was renewed to extend it's validity period.
=> Fix sha256 for bazel-release.pub.gpg

container/pull.bzl, testing/e2e/puller.sh
Follow-up from my comment here https://github.com/bazelbuild/rules_docker/pull/1222#discussion_r421995883
Added some input validation to get a nicer user error message than: 
```
PULLER_TIMEOUT=foo bazel run //foo:bar-image
- /Users/jbelotti/work/data-science/WORKSPACE:275:1
ERROR: An error occurred during the fetch of repository 'base_image':
invalid literal for int() with base 10: "foo": For input string: "foo"
```
=> Fix bug in image puller execution timeout

repositories/go_repositories.bzl
We want to support this import fix: https://github.com/google/go-containerregistry/issues/717
=> Updated go-containerregistry version

testing/examples/run_instruction_arbitrary/BUILD, testing/examples/run_instruction_arbitrary/Dockerfile
Python2 now fails to install the same packages probably due to its deprecation.
=> Switch arbitrary run instruction to python3

container/BUILD, container/build_tar.py, repositories/repositories.bzl, repositories/requirements-pip.txt, testing/custom_toolchain_auth/WORKSPACE, testing/custom_toolchain_flags/WORKSPACE, testing/default_toolchain/WORKSPACE, testing/download_pkgs_at_root/WORKSPACE, testing/e2e.sh, testing/e2e/top_level.sh, testing/examples/WORKSPACE, testing/java_image/WORKSPACE, testing/new_pusher_tests/WORKSPACE
Next version of Bazel is expected to stop providing gflags via Bazel tools according to #1533
=> Revert to using gflags but use it from a pips package instead of Bazel Tools

container/BUILD, container/archive.py, container/build_tar.py, testdata/BUILD, testdata/extras_gen.py
=> Add archive manipulation logic from rules_pkg

repositories/go_repositories.bzl
This will fix issue https://github.com/bazelbuild/rules_docker/issues/1567 which causes non-hermetic builds is using the `container_bundle` rule with multiple images.
=> [Update] go-containerregistry to fix `container_bundle` rule

container/image.bzl, docker/package_managers/apt_key.bzl, docker/toolchain_container/debian_pkg_tar.bzl
The image rule in container/image.bzl was symlinking the config file for
strutcture tests. This caused remote execution with
--remote_download_minimal to fail as symlinks aren't yet supported.
=> Change image rule to copy config instead of symlink

container/BUILD, container/build_tar.py, repositories/requirements-pip.txt, testing/custom_toolchain_auth/WORKSPACE, testing/custom_toolchain_flags/WORKSPACE, testing/default_toolchain/WORKSPACE, testing/download_pkgs_at_root/WORKSPACE, testing/e2e/top_level.sh, testing/examples/WORKSPACE, testing/java_image/WORKSPACE, testing/new_pusher_tests/WORKSPACE
Since https://github.com/bazelbuild/rules_docker/pull/1535, rules_docker depends on a global `@pip_deps` external repo and pip to install the python gflags library. This easily conflicts with other python rules that claim that name (https://github.com/bazelbuild/rules_docker/issues/1404) and forces a dependency on pypi, making rules_docker harder to depend upon. I'd prefer not to have to setup a pypi mirror just to be able to reliably use rules_docker.
This seems pretty painful for importing a flag library, the comment in https://github.com/bazelbuild/rules_docker/issues/1533#issuecomment-644153801 suggests
> Or... just replace the single use of gflags with the python flag library. It is only container/build_tar
Which this PR attempts to implement.
=> Replace dependency on gflags with argparse

container/pull.bzl
repository_ctx.read exists specifically to read the content of a file.
`cat` is not available on all platforms (notably Windows).
=> Simplify reading the digest file obtained when pulling a Docker image

container/go/cloudbuild.yaml
First step towards addressing https://github.com/bazelbuild/rules_docker/issues/1155
=> Add Linux ARM64 go pusher and loader binaries to cloudbuild

container/go/cloudbuild.yaml
The location and naming of go binary artifacts changed when rules_go was updated in https://github.com/bazelbuild/rules_docker/commit/db48e7c187f42a0a4fcaaa9ce90c2748fff11b68. This is likely due to the changes in https://github.com/bazelbuild/rules_go/commit/695da5906684ab96e558c3159f7d88a20a6a1703 and https://github.com/bazelbuild/rules_go/commit/7a2ed944ae81f5c896e876e0c0975e9900832334.
Since builds on all platforms now place the artifacts in the same location, the darwin build can only begin once the linux uploads are complete.
=> Update puller and loader locations and sequencing in cloudbuild

README.md, container/BUILD, container/go/cloudbuild.yaml, container/go/cmd/zipper/BUILD, container/go/cmd/zipper/zipper.go, container/import.bzl, container/layer.bzl, skylib/zip.bzl, testing/default_toolchain/WORKSPACE, tests/container/BUILD, toolchains/docker/toolchain.bzl
This is mostly for consistency across platforms, and to remove an external dependency.
=> For gzip operations, use a new Go helper by default instead of which(gzip)

container/layer.bzl
Otherwise, the .tar file gets a weird structure that is not well interpreted in Linux; e.g. files get names like ".\a\b\c\file" (that is a filename, not a path).
=> Fix the root directory when building for Linux on Windows.

container/push.bzl
This attribute allows to set the repository value from a file as it is
already possible for the tag thanks to the tag_file attribute.
=> Add repository_file attribute to the container_pull rule

repositories/go_repositories.bzl
`go_repository` git `commit` doesn't support `http_load` caching mechanism thus prevents `rules_docker` to be used in air gapped environment.
Replacing it with alternative `urls` address makes go_repository to use `http_load` and utilize [caching mechanism](https://docs.bazel.build/versions/master/guide.html#running-bazel-in-an-airgapped-environment) if needed.
An additional piece of information will be needed in future for updating dependencies' versions - sha256.
The way to get sha256 on mac - to download the file from `https://api.github.com/repos/<org>/<repo>/tarball/<commit>` and running `shasum -a 256 <file>`
=> Support airgapped environment

README.md
There are a few typos in root README.
=> Fix the typos in root README

container/build_tar.py, container/layer.bzl
Notably, it replaces slashes with backslashes.
=> Avoid using os.path.normpath on Windows with files destined for Linux.

docker/util/commit.sh.tpl
The shell expansion prints many unnecessary verbose debug lines into the bazel build log. Let's stop doing that.
=> Reduce build verbosity of container_run_and_commit

container/BUILD, container/push-tag.bat.tpl, container/push.bzl
- Use a batch file instead of a shell script.
- Fix paths by using backslashes.
=> Support container_push on Windows.

repositories/py_repositories.bzl, repositories/repositories.bzl
Note that users who install their own rules_python will need to update that together with their rules_docker
=> Update for compatibility with rules_python 0.1

contrib/cmp_images.sh.tpl, docker/package_managers/download_pkgs.bzl, docker/package_managers/installer.sh.tpl, docker/package_managers/run_download.sh.tpl, docker/package_managers/run_install.sh.tpl, docker/util/commit.sh.tpl, docker/util/commit_layer.sh.tpl, docker/util/extract.sh.tpl, docker/util/image_util.sh.tpl, testdata/cc_image_wrapper.sh, testing/download_pkgs_at_root/download_pkgs_at_root_run_test.sh, tests/container/architecture_test.sh, tests/container/pull_info_validation_test.bzl, tests/contrib/compare_ids_fail_test.sh.tpl, tests/contrib/mv_project_root.sh, tests/contrib/rename_image_test.sh, tests/docker/package_managers/download_pkgs_run_test.sh, tests/docker/package_managers/download_pkgs_with_additional_repos_run_test.sh, tests/docker/package_managers/test_complex_packages.sh
Not all operating systems ship with bash located at `/bin/bash`. Change the interpreter to `/usr/bin/env bash` to request bash from the environment.
For instance, I use [NixOS](https://nixos.org) as my daily driver and this operating system does not follow [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard); In fact it does not have a `/bin` and the only thing in `/usr/bin` is `env`.
Related to https://github.com/bazelbuild/rules_go/pull/2295
=> Use bash from the environment instead of absolute path

README.md
Point to release notes from the README to get the release specific copy paste `http_archive` rule to download rules_docker. This avoids having to update the README after each release. Only expected to work for release [v0.15.0](https://github.com/bazelbuild/rules_docker/releases/tag/v0.15.0) onwards
=> Remove release pin from README

contrib/push-all.bzl, contrib/push-all.sh.tpl
There seems to be a bug with pushing many images (50+) related to the
async+wait behavior previously used, and this new option will give users
who have lots of images to push a safer option.
Fixes https://github.com/bazelbuild/rules_docker/issues/525
=> Add option to push images sequentially in push-all

cc/cc.bzl, container/go/cmd/update_deps/BUILD, container/go/cmd/update_deps/update_deps.go, go/go.bzl, java/java.bzl, java/jetty.bzl, python/python.bzl, python3/python3.bzl, repositories/go_repositories.bzl
Suggest reviewing commit by commit.
In #1655, I ran into issues where `update_deps.sh` provided invalid digests. My belief is that
distroless started shipping multi-platform images (`linux/amd64` and `linux/arm64`), so `crane`
was grabbing the multi-platform manifest instead of the `linux/amd64` digest. In the first two
commits, I
1. upgrade external repos to latest version of `crane`
2. add `linux/amd64` platform as default to `update_deps` binary
Then I
3. ran the new `update_deps.sh`, and it produced valid digests.
~Open Q: presumably, rules_docker will want to support arm images at some point? Future work?~ Answered my question here: https://github.com/bazelbuild/rules_docker/issues/1155#issuecomment-571149145
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Fix update_deps to grab correct platform digest, rerun

container/load.bzl, container/pull.bzl, repositories/repositories.bzl
Similar to what https://github.com/bazelbuild/rules_docker/pull/1661 does for s390x.
=> Add arm64 support to load puller and loader binaries

container/push.bzl
The backslash used for Windows paths needs to be escaped itself. This was okay because `\{` is an invalid escape sequence which was ignored; but now they'll throw errors due to https://github.com/bazelbuild/bazel/commit/73402fa4aa5b9de46c9a4042b75e6fb332ad4a7f.
=> Fix invalid escape sequence

contrib/BUILD
Bazel is changing how @bazel_tools/conditions:darwin is implemented.
With old implementation based on flags, it was ok to have darwin and
darwin_x86_64 in a select. This was based on flag --cpu=darwin and
--cpu=dawin_x86_64.
New implementation is based on constraints, where "darwin" means OS (and
any CPU), while "darwin_x86_64" mean only specific CPU. As such they
cannot be used in the same select, because the selection would be
ambiguous.
=> Fix select with condition on darwin.

container/BUILD, container/image.bzl, container/image_test.py, container/providers.bzl, testdata/BUILD
The Stamp attribute is now properly prorivded from the base image to the
child image which ensures that target image will be created with default
timestamp value.
```starlark
container_image(
name = "with_stamped_creation_time",
base = ":base_with_volume",
stamp = True,
)
container_image(
name = "with_base_stamped_image",
base = ":with_stamped_creation_time",
)
```
Related to #155
=> Fix Stamp param propagation from base image

container/BUILD, container/bundle.bzl, container/go/cmd/join_layers/join_layers.go, container/image.bzl, container/import.bzl, container/layer_tools.bzl, testdata/BUILD
This adds an attribute that controls the format of the image tarball
produced when building container_image as "${name}.tar".
The current behavior is a legacy, uncompressed format that is compatible
with older versions of docker but suboptimal for most use cases. I have
retained the default behavior by setting the default value to "legacy",
but callers can opt into a newer format by setting this to "compressed".
In the future, we may want to add support for an OCI Image Layout as
well.
See: https://github.com/bazelbuild/rules_docker/issues/1695
=> Add experimental_tarball_format to container_image

container/push.bzl
This allows the pusher to be referenced as a label without including all the default outputs including the .digest file
Fixes #1684
Also use the user-provided value for the (undocumented) "extension" parameter if one is set.
Fixes #1683
=> Introduce output_group for pusher executable

testing/examples/run_instruction_arbitrary/BUILD, testing/examples/run_instruction_arbitrary/Dockerfile
The tests are using a base image that only has python3.5.
Currently the `//testing/examples/run_instruction_arbitrary:all` tests are failing with
```
stderr: Traceback (most recent call last):
File "/usr/local/bin/pip", line 7, in <module>
from pip._internal.cli.main import main
File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
^
SyntaxError: invalid syntax
```
This was fixed upstream in https://github.com/pyenv/pyenv/pull/1793 but it is not clear to me how/when we can expect to see that as part of launcher.gcr.io/google/bazel:latest.
=> Fix tests resulting from pip dropping support for legacy Python

container/go/cmd/digester/digester.go, container/go/pkg/compat/reader.go
This was supported before, but was removed as part of https://github.com/bazelbuild/rules_docker/pull/1123, a performance optimization/refactoring change. I am proposing to add back the support without changing the code path if the other inputs are available, so current users are not affected.
=> Support computing the digest when caller can only specify --tarball.

README.md, WORKSPACE, rust/image.bzl
As of https://github.com/bazelbuild/rules_rust/commit/1fe23158e5316c17b2ee2a252ee7165c5d83cc93 the workspace name for the Bazel Rust rules is `rules_rust`. This PR is to reflect that change in the docker rules.
=> Renamed `io_bazel_rules_rust` to `rules_rust`

README.md
At [Domino Data Lab](https://www.dominodatalab.com/), we're using `rules_docker` to build Docker images in our monorepo. Hopefully our usage encourages others to adopt `rules_docker` as well.
=> Add Domino Data Lab to list of adopters

.github/CODEOWNERS, CODEOWNERS, README.md
We got the new maintainers here now, and don't need to advertise this way.
We'll surely add more maintainers from the community over time, but can bootstrap that the normal way by promoting ppl who are active and helpful in the repo.
This reverts commit a4d580ee357b3e40e80becb311ea88214b70e0db
and moves the config file to .github/ folder to improve tidiness in the root
=> Revert "Invite maintainers from community (#1750)"

README.md
It was fixed over a year ago according to https://github.com/bazelbuild/rules_go/issues/2089
I've had some users confused by this message since we tell them to use this rule on Mac
=> Remove warning about go_image on Mac

.github/workflows/stale.yml
If an issue or PR goes 180 days without comments, and has no assignee, then add a nice warning comment and add a "Can Close?" label.
If it then goes another 30 days without comments or assignee, then close it with a nice comment.
Note that after this is merged, we'll need to also enable this in the Actions tab of the repo settings.
Closes #1752
=> Introduce github action to mark stale issues/PRs

.github/workflows/size-label.yml
This replaces a bit of automation we were getting from the k8s-ci-robot
=> Setup assign-size-label action

contrib/test.bzl
=> Propagate tags to the container image test bundle

cc/cc.bzl, container/go/cmd/update_deps/update_deps.go, go/go.bzl, go/static.bzl, java/java.bzl, java/jetty.bzl, nodejs/nodejs.bzl, python/python.bzl, python3/python3.bzl
This script finds reproducable hashes for pulling containers from
distroless. Since the last time this was run it seems that they
have stopped pushing a :debug tag for some images (static). This
makes sense as static is just an image with some standard openssl
and user file deps that do not have debug versions.
The code that implements update_deps is written to recover from
this situation (seemingly anticipating it) but it looks like the
author copied a Fatalf which os.Exit(1)s after printing. I've
changed this ti a Printf() so that the existing recovery logic
can take over.
=> update_deps: Correctly check if manifest pull failed

cloudbuild.yaml
This reverts commit 1df35d946009b659306a8274b235bab83cf5c439.
We need to do more work to determine whether there was some coverage here.
=> Revert "Remove google cloud build integration (#1767)"

WORKSPACE
Build is Red
This lets it pass on my local machine, lets see what it does in CI
=> fix the build

docker/package_managers/download_pkgs.bzl, docker/package_managers/installer.sh.tpl, docker/package_managers/run_download.sh.tpl, docker/package_managers/run_install.sh.tpl, docker/util/commit_layer.sh.tpl, docker/util/extract.sh.tpl
Using these two rules is very loud and spammy in my terminal. Before my change, you get this:
```
$ bazel test //tests/docker/package_managers:gpg_test
<some stuff from this repo that doesn't affect people who just use this rule>
INFO: From Action external/debian9/builder_output_tar.tar:
++ guess_runfiles
++ '[' -d bazel-out/darwin-fastbuild/bin/external/debian9/builder_script.sh.runfiles ']'
++++ dirname bazel-out/darwin-fastbuild/bin/external/debian9/builder_script.sh
+++ cd bazel-out/darwin-fastbuild/bin/external/debian9
+++ pwd
++ mydir=/private/var/tmp/_bazel_paul.tarjan/6f5fd31832ce262640c512a62fb62896/sandbox/darwin-sandbox/2002/execroot/io_bazel_rules_docker/bazel-out/darwin-fas …
```
=> make downloading and installing quieter

.bazelci/presubmit.yml, container/layer_tools.bzl, docker/util/run.bzl
[RBE](https://buildkite.com/bazel/rules-docker-docker/builds/5287#2e3a558e-5267-4540-93b5-bf2f19ae14ab) builds are currently failing when testing `//tests/docker/util:all` with the following error
```
(20:05:17) ERROR: /workdir/tests/docker/util/BUILD:89:16: ExtractConfig tests/docker/util/test_container_commit_image.test_container_commit.build.config failed: (Exit 1): extract_config failed: error executing command
(cd /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/io_bazel_rules_docker && \
exec env - \
bazel-out/host/bin/container/go/cmd/extract_config/extract_config_/extract_config -imageTar …
```
=> Fixed broken `//tests/docker/util:all` tests

WORKSPACE, tests/docker/toolchain_container/BUILD
When building these rules, there's currently a large list of warnings coming from various things within the workspace.
```
(23:38:49) DEBUG: Rule 'ubuntu1604' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "eb50020790e22538676e17c0242b9272bdb5c81f7bc6b128a4abfa7ad31faf5b"
(23:38:49) DEBUG: Repository ubuntu1604 instantiated at:
/workdir/WORKSPACE:226:13: in <toplevel>
Repository rule http_archive defined at:
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(23:38:49) DEBUG: Rule 'debian9' indicated that a …
```
=> Fixed some missing digests and addressed other warnings

go/static.bzl
This PR closes #1642 .
This PR is possible due to the merging of https://github.com/GoogleContainerTools/distroless/pull/695.
The change in this PR was done by running `bazel run //container/go/cmd/update_deps -- --repository=gcr.io/distroless/static --output=$PWD/go/static.bzl`.
CC: @kalbasit
=> Use actual sha for static:debug image (and update static:latest)

repositories/go_repositories.bzl
- [n] Tests for the changes have been added (for bug fixes / features)
- [n] Docs have been added / updated (for bug fixes / features)
Issue Number: #1814
This updates the go-containerregistry dependency from [0.1.4](https://github.com/google/go-containerregistry/releases/tag/v0.1.4) (October 2020) to [0.4.1](https://github.com/google/go-containerregistry/releases/tag/v0.4.1) (March 2021)
This removes a dependency on a non-deterministic package resulting in inconsistent archive SHAs generated by GitHub's archive server. That upstream issue was also fixed in https://github.com/kubernetes/kubernetes/issues/99376.
Other than removing this non-determinism, no major functional changes are …
=> Update go-containerregsitry dependency to 0.4.1

container/BUILD, container/image.bzl, repositories/repositories.bzl
First step to fixing https://github.com/bazelbuild/rules_docker/issues/1751
=> Add stardoc API doc generation

container/image.bzl, container/layer.bzl
These affect stardoc calculation of the auto-dedent
=> fix tab characters in docstrings

cc/image.bzl, d/image.bzl, go/image.bzl, groovy/image.bzl, java/image.bzl, kotlin/image.bzl, python/image.bzl, python3/image.bzl, rust/image.bzl
We are using `py3_image()` with `layers` parameter in one of our projects. These images have `tags = ["manual"]` so we don't expect them to build with `bazel build //...`. However, we observing that `.tar` files with layers are still built. That happened because tags were not propagated to the layer's targets. This PR is trying to fix the issue.
`bazel build //...` doesn't build extra targets like layers when manual tag is used.
=> Propagate tags to app-layers in docker images for all langs

container/layer_tools.bzl, skylib/zip.bzl
=> Don't upload large files to remote-cache

container/archive.py, tests/container/BUILD, tests/container/build_tar_test.py, tests/container/testdata/BUILD
Long file names in tar files can't be moved into a sub folder using `container_image`.
Issue Number: https://github.com/bazelbuild/rules_docker/1848
Files are moved into the correct folder
If someone was relying on the behavior of long file name truncation their container's images will break.
Not yet complete. I need to dig into why this fix works.
=> build_tar: Support tar archives with file names longer than 99 chars

README.md
Docs point to a target that has since moved.
Docs point to the new target.
=> Correct container_py_toolchain target

README.md
The .travis.yml is no longer; this PR updates the readme to reflect that.
=> [ci] Remove travis badge

container/layer_tools.bzl, testdata/BUILD, testdata/flag_main.go, testing/e2e/flag.sh, testing/e2e/test_flag.yaml
Closing issues: #1486 and #1441.
Currently any command-line arguments (except for `--norun`) to `bazel run` are ignored.
To maximize compatibility between `<lang>_binary` and `<lang>_image`, this PR allows passing command line arguments after `--` to `bazel run`.
For example, now `bazel run //path/to:my_image -- --arg1="hello world" --arg2="how are you?"`, will pass `--arg1` and `--arg2` to the end of the `docker run` command, which will in turn pass them to the binary.
=> Allow passing command line arguments during `bazel run`

.bazelci/presubmit.yml
This PR updates the buildifier CI warning list.  Before, we were iterating the list of warnings to check for.  After, we will only list those to exclude.
Future PRs can be submitted to remove those exclusions.
=> Update buildifier warnings

container/layer.bzl, docker/package_managers/install_pkgs.bzl, docker/util/run.bzl
Similar to #1856. I found these by patching that PR and running through a big monorepo and searching execution log for more remote cache uploads over 10MB
=> More fixes for actions that shouldn't upload to remote-cache

.bazelci/presubmit.yml, .pre-commit-config.yaml, CONTRIBUTING.md
Based on what just merged into rules_apple: https://github.com/bazelbuild/rules_apple/commit/61bc7c01aeee1324dc276e4f09bba88913ab2a62
=> Add buildifier pre-commit hook and instructions

container/archive.py
No tests have been changed or added, but existing tests should validate the new behaviour still results in valid images
Currently, rules_docker when executed on windows will build a tar file with `\` characters in the tar, this works fine when opened with tools like 7z, however, when extracting using a typical `tar` tool (or when docker does it), the files end up mangled with <dirname>\<filename>` all jumbled up together in their file name
This is because archive.py makes a lot of assumptions about posix paths using `/` characters, but then bundles this up with also using `os.path` instead of `posixpath`
This fixes this problem by using `posixpath` in `archive.py`
I …
=> Fix path handling in archive.py to always be posix and not native paths

repositories/go_repositories.bzl
When executing the repository rule `com_github_google_go_containerregistry`, the following warning is printed:
```
DEBUG: /private/var/tmp/_bazel_martin/37de97fe4a6bb79f99ddaabf4bd12042/external/bazel_gazelle/internal/go_repository.bzl:184:18: com_github_google_go_containerregistry: gazelle: finding module path for import github.com/vdemeester/k8s-pkg-credentialprovider: exit status 1: go: finding module for package github.com/vdemeester/k8s-pkg-credentialprovider
go: found github.com/vdemeester/k8s-pkg-credentialprovider in github.com/vdemeester/k8s-pkg-credentialprovider v1.21.0
go: github.com/vdemeester/k8s-pkg-credentialprovider@v1.21.0 requires
k8s.io/kubelet@v0.0.0: reading …
```
=> Silence go module warnings in go_repository

repositories/go_repositories.bzl
This is a no-op change.
These URLs have a few advantages:
* GitHub is less aggressive at rate-limiting these URLs, and these URLs
are easier to set up pass-through proxies for in an enterprise
setting.
* The URLs self-document which tag is being fetched, rather than
requiring separate comments to track tags (but the sha256 ensures
re-pointed tags will still halt builds). That said, there are
sha1-equivalent URLs if we'd prefer to keep them.
* The URLs have file extensions, so don't need a separate `type`
attribute
=> Switch to non-api fetch URLs

container/build_tar.py, tests/container/build_tar_test.py
EDIT: the bug itself isn't about writing base64 files, it's about writing the filename instead of parsing Package information from the metadata file.
~~Fixes a bug where dpkg/status.d writes base64 data instead of human readable strings
`var/lib/dpkg/status.d/YmFzZS1maWxlcw==` vs  `var/lib/dpkg/status.d/base-files`~~
Signed-off-by: Appu Goundan <appu@google.com>
Honestly can't get tests running locally, bazel is so unfamiliar, I'm pretty confused. But I ran against distroless using my local copy and it seems to work.
https://github.com/GoogleContainerTools/distroless/issues/787
https://github.com/GoogleContainerTools/distroless/issues/581 …
=> Update convert bytes to string for py3

README.md, container/layer.bzl, testing/default_toolchain/WORKSPACE, testing/default_toolchain/local_tool.bzl, toolchains/docker/BUILD.tpl, toolchains/docker/toolchain.bzl
This PR is a re-opening of https://github.com/bazelbuild/rules_docker/pull/1559, which was closed due to inactivity.
You cannot provide the `xz` dependency via a Bazel http_archive, instead you must have `xz` already installed on the system, which is not feasible in heterogeneous build environments.
Allows a hermetic xz binary to be provided.
Worth noting that busybox provides a fully static musl busybox that
should work on any Linux system, that gives you both gzip and xz.
---
787a9560 feat(toolchain): add xz_target for remote execution
Copied what is currently done for gzip_target.
<br/>
=> feat(toolchain): add xz_target for remote execution

.bazelci/presubmit.yml
Not sure why this started failing. I'll investigate sometime in the future when I have access to MacOS hardware.
=> Temporarily Disable some //test/container tests in Mac

toolchains/BUILD, toolchains/docker/BUILD
=> Do not use constraints from bazel_tools

WORKSPACE, rust/image.bzl
Rules rust has made some changes upstream that remove the rust.bzl file.
It had previously been left in there for compatibility purposes.  This
has been ongoing since February 16th.  See this issue for additional
context: https://github.com/bazelbuild/rules_rust/issues/591.  Replaces
PRs #1950 and #1951.
Fixes #1949
=> Update to a more recent rules rust and update to use defs.bzl

container/go/cmd/digester/digester.go, container/go/cmd/flattener/flattener.go, container/go/cmd/pusher/pusher.go, container/go/pkg/compat/reader.go
Turns out rules_k8s also depended on the ReadImage function. If anyone
else is depending on this, we can maintain backwards compatibility by
keeping the same function signature and having it wrap
Reader.ReadImage().
=> Maintain old API for backwards compatibility.

.bazelci/presubmit.yml, groovy/image.bzl, java/image.bzl, kotlin/image.bzl, scala/image.bzl, tests/container/groovy/BUILD, tests/container/groovy/configs/groovy_classpath_as_file_image.yaml, tests/container/java/BUILD, tests/container/java/configs/java_classpath_as_file_image.yaml, tests/container/kotlin/BUILD, tests/container/kotlin/configs/kt_jvm_classpath_as_file_image.yaml, tests/container/scala/BUILD, tests/container/scala/configs/scala_classpath_as_file_image.yaml
Callers of `jar_app_layer` can not specify `_classpath_as_file`.
Yes. It changes the `jar_app_layer._classpath_as_file` private attribute to a public attribute `jar_app_layer.classpath_as_file`. This allows callers to override the default value of `False` when applying the `jar_app_layer` rule.
The PR also make the callers of `jar_app_layer` expose an optional `classpath_as_file` argument so that folks can passthrough the argument to `jar_app_layer`.
Some details of why someone would want to do this can be found in the [Bazel slack](https://bazelbuild.slack.com/archives/CA3NW13MH/p1635778927010700?thread_ts=1635545233.009800&cid=CA3NW13MH)
Given that the `classpath_as_file` was private …
=> Make jar_app_layer._classpath_as_file public

container/pull.bzl, docs/BUILD, docs/container.md, repositories/repositories.bzl
The PULLER_TIMEOUT env variable is convenient, but one very large image shouldn't require that all of them have timeouts changed.
=> feat: add timeout attribute to container_pull

WORKSPACE, contrib/dockerfile_build.bzl, testdata/dockerfile_build/Dockerfile, tests/contrib/configs/dockerfile_image.yaml
I wasn't able to build a specific stage of a Dockerfile with the current implementation of `dockerfile_build`
You can optionally specify a `target` attribute for `dockerfile_build` that will tell docker to build to that stage. [Docker documentation here](https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage---target)
=> Add target as an attribute to dockerfile_build

testing/examples/WORKSPACE
In `testing/examples`, running `bazel test //...` yields the following warnings that digests of the images being used are not specified:
```
DEBUG: Rule 'ubuntu1604' indicated that a canonical reproducible form can be obtained by modifying arguments digest = "sha256:8f0b64fd212007183434b8b3271b723700ab14e4230b5bec1415b79aaa3ac97b"
DEBUG: Repository ubuntu1604 instantiated at:
/home/t/rules_docker/testing/examples/WORKSPACE:51:15: in <toplevel>
Repository rule container_pull defined at:
/home/t/.cache/bazel/_bazel_t/8f44971fccf59391c1b86a62b75f492c/external/io_bazel_rules_docker/container/pull.bzl:270:33: in <toplevel>
DEBUG: Rule 'bazel_image' indicated that a canonical reproducible …
```
=> Add digests of the images being used for examples

container/push.bzl
Add the label to the warning message about setting a tar on a push rule. 
In a large repo, the source of this warning is tricky to track down without the label of the rule being present in the message.
=> fix: add label to tar warning message

contrib/push-all.bzl
Generally `--skip-unchanged-digest` is a very useful flag to have. One can simply setup a release pipeline upon successful CI to just do `bazel run <push-all-target>` to push all container images (wrapped in a container bundle) at once.
By checking against upstream registry whether an existing digest already existed, we will only push images which were updated as the result of recent changes introduced to the repo.
The alternative solution is to calculate the SCM diff (git-diff) of the repo to deduce which bazel target were affected, query for container_push targets and `bazel run` each target 1-by-1, which is complicated to setup (especially when handling deleted code).
---
This PR added the ability to verify unchanged digest to bundle push (contrib/push-all) rule for convenience. …
=> container_push: add skip_unchanged_digest attribute

docker/package_managers/run_install.sh.tpl
These print a ton of output from arbitrary commands in the container, like dpkg spam for hundreds of lines.
Well-behaved Bazel actions should be silent when successful to avoid making bazel stdout unreadable.
=> Don't print output of ExtractImageId mnemonics when successful

cc/cc.bzl, go/go.bzl, go/static.bzl, java/java.bzl, java/jetty.bzl, nodejs/nodejs.bzl, python/python.bzl, python3/python3.bzl
This update was initiated mainly to update `cc_image` distroless image to debian11
distroless images have moved to debian11 as a default on 30/09:[https://github.com/GoogleContainerTools/distroless/issues/844](source)
`cc_image` latest digest tag `sha256:2c4bb6b7236db0a55ec54ba8845e4031f5db2be957ac61867872bf42e56c4deb`
still points to a debian10 image: 
```
$ docker run gcr.io/distroless/cc@sha256:2c4bb6b7236db0a55ec54ba8845e4031f5db2be957ac61867872bf42e56c4deb /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Debian GLIBC 2.28-10) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO …
```
=> update distroless images

container/bundle.bzl, docs/container.md
There was a concern raised in Bazelbuild Slack that the use case of
container_bundle is not clear to newer users.
Add the 2 known use cases of container_bundle to rule's doc.
=> container/bundle.bzl: improve bundle rules doc

container/BUILD, container/layer_tools.bzl, contrib/automatic_container_release/BUILD, contrib/automatic_container_release/configs_test.bzl, docker/package_managers/BUILD, docker/package_managers/download_pkgs.bzl, docker/package_managers/install_pkgs.bzl, docker/util/BUILD, docker/util/run.bzl, skylib/BUILD, skylib/docker.bzl, toolchains/docker/BUILD.tpl, toolchains/docker/readme.md, toolchains/docker/toolchain.bzl
Regarding 👇, do you have docs about how to add tests and how to generate docs?
Currently, there is no way to supply a docker client as a target, which requires you to install docker not part of Bazel
Just like the other tools in the toolchain (gzip, xz), you can supply `docker_target` in order to get the docker client from bazel
=> Add tool target attribute to docker toolchain

README.md, container/layer.bzl, testing/default_toolchain/WORKSPACE, toolchains/docker/BUILD.tpl, toolchains/docker/toolchain.bzl
Current behavior of `build_tar` tool used by `container_layer` is not hermetic, because it implicitly depends on the python toolchain, and as demonstrated by  #1680, this can lead to non-reproducible builds.
Similar to #1881, this PR adds an optional attribute for toolchain configuration, allowing to pass a hermetic `build_tar_target` executable.
=> toolchain: allow to configure build_tar target

nodejs/image.bzl
=> feat(): allow rules_docker to work with rules_nodejs 5.x when it updates

.bazelrc
`--incompatible_disable_depset_items` is removed at Bazel@HEAD and is turned on by default in 5.0.
See https://github.com/bazelbuild/rules_docker/pull/1977#issuecomment-998651425
=> .bazelrc: remove --incompatible_disable_depset_items

repositories/deps.bzl, repositories/go_repositories.bzl
Issue Number: https://github.com/bazelbuild/rules_docker/issues/1902
Users can now use `WORKSPACE.bazel` files by setting `go_repository_default_config`:
```python
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
container_deps(
go_repository_default_config = "@//:WORKSPACE.bazel"
)
```
=> Allow support for `WORKSPACE.bazel` files

container/layer_tools.bzl
The `docker run` command fails because it is missing a `run_tag` arg due to a missing line merged in #1957.
The `docker run` command succeeds and runs as per documentation.
The line `"%{run_tag}": run_tag,` was omitted during this merge commit:
https://github.com/bazelbuild/rules_docker/pull/1957/commits/922e4662e97ed050023248b77ca015a35ac1715c#diff-2a6edca3d784a368586063a7774b7551bbf4476c7345c511ab987bf95c610527L281
Referenced in this comment on the original PR:
https://github.com/bazelbuild/rules_docker/pull/1957#issuecomment-1007904580
=> Add missing `run_tag` directive.

container/incremental_load.sh.tpl
Currently running something like the following produces an error `container_args[@]: unbound variable`
```
bazel run //tests/container/python3:py3_image -- --rm -it --entrypoint /bin/bash
```
Issue Number: This is a minor bugfix to https://github.com/bazelbuild/rules_docker/pull/1957
This fixes the issue and I'm able to run my container and start a bash shell based on the arguments above.
=> Fix unbound variable when running container_image targets

testing/README.md, testing/e2e.sh
Currently, you can run all e2e tests or nothing.
Issue Number: #1997
You can run a single e2e test.
=> Enable to run a single e2e test

testing/default_toolchain/WORKSPACE
```
$ cd testing/default_toolchain/
$ bazel cquery --override_repository=io_bazel_rules_docker=/home/user/bazelbuild/rules_docker '@docker_config//:*'
INFO: Invocation ID: b42e2f4d-afa1-4269-8594-21b2babb178e
INFO: Repository build_tar instantiated at:
/home/user/bazelbuild/rules_docker/testing/default_toolchain/WORKSPACE:29:11: in <toplevel>
Repository rule local_tool defined at:
/home/user/bazelbuild/rules_docker/testing/default_toolchain/local_tool.bzl:37:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'build_tar':
Traceback (most recent call last):
File "/home/user/bazelbuild/rules_docker/testing/default_toolchain/local_tool.bzl", line 27, column 17, in …
```
=> Replace non existing "build_tar" local tool with a repo target

container/BUILD, container/go/cmd/sha256/BUILD, container/go/cmd/sha256/sha256.go, container/image.bzl, container/import.bzl, container/layer.bzl, docker/util/run.bzl, docs/container.md, skylib/BUILD, skylib/hash.bzl
^^ unsure if this is necessary; existing tests probably cover?
sha256 computation depends on https://github.com/bazelbuild/bazel/tree/master/tools/build_defs/hash which requires external python.  We can replace this with a simple Go cmd.
Issue Number: #1555
=> remove dependency on external python for sha256

container/layer.bzl, container/layer_tools.bzl, docker/package_managers/install_pkgs.bzl, docker/util/run.bzl, skylib/zip.bzl
These were introduced to reduce load on a remote-cache instance to avoid network saturation.
A month later, a feature was added in one remote-cache implementatation which provides a different fix:
https://github.com/buchgr/bazel-remote/issues/440 rejects large input files on upload.
In practice, while these action do often produce huge outputs, they are also slow to re-execute.
In many cases it's worth it to use a remote-cache for RunAndCommitLayer in particular to avoid a local rebuild
even though it's a large network fetch.
Currently users can't configure this because we've hardcoded the values. If they do want to keep the
no-remote-cache execution requirement, they can do this via a tag (provided they opt-in to
experimental_allow_tags_propagation, see …
=> perf: remove no-remote-cache execution requirements

testing/e2e.sh
E2E tests
Tests are failing:
```
$ ./testing/e2e.sh test_new_container_push_with_stamp
Untagged: bazel/testdata:java_image
Deleted: sha256:eb80f78831e79eaece9b9e902ab2a806cf42c343982480fa9effa5eebc01dadd
Deleted: sha256:08d041228c55a55fc73cd9e19f1b5c0e48e2e9db9561cf31406793b9f9614ec9
Deleted: sha256:957efaa4e727e69dc84edb895ad905ae0b0fca30a3fca0ac14bae93dfcdc571f
Deleted: sha256:6801a054c34b4d3fa6ac55f86851b7e7add658b9f6aeea3cda921676d3326e61
Deleted: sha256:85b9a170b808007c1306bbffa8bccc8d737043fa5ed84ae6bff1ad96e85c4be0
Deleted: sha256:cc2aadc8d4ba1fab738a59d14ae92c67b5866476ebb0ba176634e480ae5f7b9c
Deleted: sha256:033fdf5c04846c6cfc205c9e0137e8f92efa7c008cd30cc2472063a2f237e4a9 …
```
=> Stamp e2e tests

container/incremental_load.sh.tpl
On MacOS 12.3, Apple removed the default `python` executable.
Building images doesn't work and throw this error:
`env: python: No such file or directory`
Issue Number: #2046 2046
Build on a system without `python` executable (as MacOS 12.3+) works as expected.
=> Replace python with python3 in incremental_load.sh.tpl

container/incremental_load.sh.tpl
Currently when using `bazel run` on a docker image, I get:
```
/[redacted].executable: line 281: docker_args[@]: unbound variable
```
Alternatively, we could just `set +u` before execing docker.
=> Run script allows empty docker_args

container/push.bzl
In https://github.com/bazelbuild/rules_docker/pull/1118/, the warning
message was mistakenly renamed from `docker_build` to `container_build`.
`container_build` does not exist in the repository, only `docker_build`
does.
=> Fix warning message ref invalid rule

container/layer_tools.bzl
incremental_load is used for both defining single container targets and container_bundles. Defining an empty `container_bundle` crashes as there's an assumption that at least one image is defined regardless. 
Issue Number: fixes #2010 
An empty `container_bundle` does not crash. We do not try to build a run command if `run` is not set to True
=> Fix empty container_bundle

WORKSPACE
For more information see https://github.com/bazelbuild/bazel/issues/15558
Unblock CI on Ubuntu
=> bazel_gpg: update SHA256

.bazelci/presubmit.yml, tests/container/BUILD, tests/container/image_test.py
This fixes #2097 wherein `image_test` fails with Python 3.9+
For future reference this commit was generated with:
```
bazel test tests/container:image_test
grep sha256: .../testlogs/tests/container/image_test/test.log  | grep Assertion | sed -r 's@AssertionError: .sha256:(.*). != .sha256:(.*).@s/\2/\1/@' > /tmp/seds
sed -f /tmp/seds -i tests/container/image_test.py
```
This test fails with Python 3.9 and it looks like the best fix is to change the golden image digests to match the new reality.
Issue Number: #2097
Just new digests in the test to match CPython 3.9 `tarfile` behavior.
Technically Python 3.9 creates a breaking changes in that the image digests generated by `rules_docker` …
=> Make golden image digests work with Python 3.9

container/image.bzl, docs/container.md
We can give the `user` parameter in the implementation function of the rule `container_image` to override the attribute of the rule.
=> Support to override ctx.attr.user in the container_image() implementation function (#2081)

container/image.bzl, container/layer_tools.bzl
Really override the ctx.attr.base attribute with the 'base' argument of
the implementattion function of the `container_image` rule.
Issue Number: #2083 
We can give the same object type to the `base` argument of the `container_image` implementation function than the `base` attribute of the associated rule.
=> Keep the same behaviour for the 'base' argument between the rule `container_image` and its implementation function (#2083)

repositories/repositories.bzl
Version 1.9.1 of the container-structure-test-darwin-amd64 binary is not compatible with MacOS Monterey. 
```
❯ ./container-structure-test-darwin-amd64
fatal error: runtime: bsdthread_register error
runtime stack:
runtime.throw(0x15e1aff, 0x21)
/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff6f0 sp=0x7ff7bfeff6d0 pc=0x102a1b5
runtime.goenvs()
/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff720 sp=0x7ff7bfeff6f0 pc=0x1027a53
runtime.schedinit()
/usr/local/go/src/runtime/proc.go:492 +0xa4 fp=0x7ff7bfeff760 sp=0x7ff7bfeff720 pc=0x102cb94
runtime.rt0_go(0x7ff7bfeff798, 0x1, 0x7ff7bfeff798, 0x0, 0x1000000, 0x1, 0x7ff7bfeff978, 0x0, 0x7ff7bfeff9a0, 0x7ff7bfeff9dc, …
```
=> Update container-structure-test binaries to v0.11.0

.github/workflows/release.yml, README.md
[Here's a demo.](https://drive.google.com/file/d/1uBiV_xlxUf4FaXDxYNwzSt8AjHGmg8Xq/view?usp=sharing)
[Here's an example release.](https://github.com/kriscfoster/rules_docker/releases/tag/v0.25.0)
Automatic release process with GitHub actions.
Issue Number: https://github.com/bazelbuild/rules_docker/issues/2102
On a tag push, the workflow will be triggered & release will be created.
```
git tag -a v0.25.0 -m ""
git push origin v0.25.0
```
=> rules_docker release github workflow

README.md, repositories/deps.bzl, repositories/repositories.bzl, testdata/BUILD, tests/container/image_test.py, tests/container/testdata/BUILD, tests/docker/toolchain_container/BUILD
pkg_tar is being referenced at a legacy location (@rules_pkg//:pkg.bzl) which will go away in a future release of rules_pkg. This PR updates rules_pkg to the latest release and fixes the references to be to the correct location (@rules_pkg//pkg:tar.bzl) which will remain correct indefinitely.
=> Update rules_pkg to the latest release.

README.md, java/image.bzl, lang/image.bzl, tests/container/java/BUILD, tests/container/java/configs/java_image_complex_external_deps.yaml
There is no rule that allows fine layering of JVM dependencies (like `py_layer`) for `java_image`s.
`JavaInfo` is forwarded by `filter_layer` and there is a rule `java_layer` which functions identically to `py_layer` that allows filtering dependencies.
I wasn't sure that building the merged JavaInfo was the best way to do this, but I think any other way requires some more intrusive changes to `java_image` - I tried with an empty JavaInfo and forwarding the JavaInfo (as the code does with PyInfo) and they result in an empty layer and a layer with all dependencies (not filtering them at all) respectively.
=> Add java_layer rule that allows fine layering of JVM dependencies (like py_layer for Python)

README.md
I was unlucky to miss all the other references to `config.json` when I was
setting up, so I named my file `client.json`, looking instead only at the label
changed by this commit.
When I later ran a `container_push` target it failed with "permission denied"
issues. I read the shell script generated by `container_push` and saw that it
passes an argument to give the path to the _directory_ of the config file,
rather than the path to the file itself.
That made me realize that I had probably given the file the wrong name; the
Docker client didn't find a `config.json` file in that directory and ignored all
other files.
=> README.md: rename `client.json` -> `config.json` in one place.

contrib/push-all.bzl
=> remove unused and redundant --stamp-info-file

container/go/pkg/compat/reader.go, tests/container/BUILD, tests/container/image_test.py
As noted in #2099, if you use `container_import` to declare foreign layers, then depend on that in a `container_image` or `container_push` as a whole-image `.tar`, you lose the foreign layer URLs, resulting in an invalid image. This is because `compat/reader.go` loads the foreign image information from the image manifest first, *then* overwrites that with the empty stub layer found in the tarball. You can observe the loss of information in the resulting image's manifest.
This used to work with the Python-language image reader, but broke in the move to the Golang pusher.
Issue Number: #2099
We load the foreign layers last so that the stub information is overwritten.
=> Load foreign layers last

contrib/push-all.bzl
This adds support for authentication to `contrib/push-all.bzl` via credentials defined in a Docker client config defined using [`docker_toolchain_configure`](https://github.com/bazelbuild/rules_docker#container_push-custom-client-configuration). The implementation follows the example of [`container_push`](https://github.com/bazelbuild/rules_docker/blob/e15c9ebf203b7fa708e69ff5f1cdcf427d7edf6f/container/push.bzl#L109-L113).
I'm not sure how to add a test-case for this. Any pointers?
=> Support authentication in contrib/push-all.bzl

cc/cc.bzl, go/go.bzl, go/static.bzl, java/java.bzl, java/jetty.bzl, nodejs/nodejs.bzl, python/python.bzl, python3/python3.bzl
It's been 10 months since the images were updated last time. 
As described in [README.md](https://github.com/bazelbuild/rules_docker#updating-the-distroless-base-images), it's better to update the distroless base images over time to pick up bug fixes and security patches :smile:
<details><summary>update_deps.sh command log</summary>
```sh
➜  rules_docker git:(update-distroless-deps) ✗ ./update_deps.sh
2022/09/30 10:05:55 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:05:55 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target …
```
=> Update distroless images with running update_deps.sh

.github/workflows/add_binaries_to_release.yml
Would like to get apple silicon working natively.
This change would move https://github.com/bazelbuild/rules_docker/pull/2033 along
Darwin arm64 binaries (puller/loader) are not prebuilt artifacts
Issue Number: Pull #2033
Darwin arm64 binaries (puller/loader) are prebuilt artifacts
=> Build darwin arm64 to ci workflow

container/flatten.bzl, container/image.bzl, container/layer.bzl, container/layer_tools.bzl, container/pull.bzl, container/push.bzl, contrib/automatic_container_release/metadata_merge.bzl, contrib/automatic_container_release/packages_metadata.bzl, contrib/compare_ids_test.bzl, contrib/passwd.bzl, contrib/push-all.bzl, contrib/repro_test.bzl, docker/package_managers/download_pkgs.bzl, docker/package_managers/install_pkgs.bzl, docker/security/security_check.bzl, docker/toolchain_container/debian_pkg_tar.bzl, docker/util/run.bzl, skylib/hash.bzl, skylib/zip.bzl, toolchains/docker/toolchain.bzl
This will be required for bazel 7.0 due to bazelbuild/bazel#17032.
=> Switch from cfg = "host" to "exec"

container/image.bzl, docs/container.md, testdata/BUILD, tests/container/BUILD, tests/container/image_test.py
rules_docker decides the name of the resulting docker image:
bazel/{target}:{name}
The repository (`bazel/` by default) and `{target}` are fine. However, we want to customize the tag part -- the thing after the colon. This patch allows customizing the last part.
Why?
====
In our case, we are always building two images for two architectures using transitions. Here is an extract of a macro that builds two containers:
Then we build two containers using outgoing transitions:
container_image(
name = "{name}-post_transition".format(name = name),
...,
)
multiplatform_image(
name = "{name}-amd64".format(name),
src_image = ":{name}-post_transition".format(name = name),
...,
)
multiplatform_image(
name = "{name}-arm64".format(name = name),
src_image = ":{name}-post_transition".format(name = name), …
=> image.bzl: implement `tag_name`

docker/package_managers/README.md, docker/package_managers/install_pkgs.bzl, tests/docker/package_managers/BUILD
Previously `output_image_name` needed to be unique across the entire build tree. When building many containers in parallel this could result in clashes between the containers without warning or error.
This patches changes `output_image_name` to be optional, with the default value being set to the current target full label making it unique across large builds.
Issue Number: #2200
When `output_image_name` is not provided by the user, it will default to full label path similiar to `container_test`.
=> Fixes `output_image_name` in install_pkgs to be optional

container/push.bzl, contrib/push-all.bzl
In container_push rule, `_pusher` executable is copied into the output
runfiles, but not directly invoked _by_ the container_push rule.  This
binary could potentially be cross-compiled by other remote executors,
and should use the 'target' config in this action.
=> Use 'cfg=target' for pusher binary

README.md
We only plan to document rules_oci.
In case anyone still wants to see what we hosted before, it's here:
https://docs-legacy.aspect.build/rules_docker
=> Remove aspect docs link

container/image.bzl, docs/container.md
Follows the pattern used for other attributes of the
container_image macro to expose overriding via the method
recommended for custom rules using the _impl() method and
image attrs.
Currently labels cannot be overriden by custom container image rules.
Labels can be overriden by custom container image rules.
=> Allow labels to be overriden by custom container_image rules

container/image.bzl
_image_config was retrieving labels from ctx instead of the
labels arg.
=> Fix label override provided by custom container_image rules

README.md
14 out of 25 issues on the first page of https://github.com/bazelbuild/rules_docker/issues have no replies.
Issues like #2213 show that releases are stalled right now.
https://github.com/bazelbuild/rules_docker/pulse/monthly shows four commits touching four files in the last month, one of those was me removing an external docs link.
I discussed this with the maintainers on the discussion thread, and we agreed to put up a message for now to better set user expectations. I also alerted the Bazel team to this change in the SIG meeting on March 7, see https://docs.google.com/document/d/1YGCYAGLzTfqSOgRFVsB8hDz-kEoTgTEKKp9Jd07TJ5c/edit#
To be clear: I greatly appreciate the effort that the current two maintainers have made, this is not a vote-of-no-confidence in their engineering abilities or …
=> chore: add maintenance status to top of README

container/image.bzl
The OCI distribution spec only allows lower case letter in container repository name
(https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests), this doesn't bode well with Bazel package path using upper case.
Relevant docker spec on 'repository name' scheme: https://github.com/moby/moby/blob/master/image/spec/v1.2.md.  Among other things: "...Name components may contain lowercase characters, digits, and separators...."
So force lower case on pkg path.
<bazel_ws>/Pkg_path_with_upper_case/ $ bazel build <:container_image_target.tar>
...
FAILED: Build did NOT complete successfully
...
Unable to process values passed using the flag --tag: unable to parse …
=> Force lower case on Bazel pkg path to play nice with oci container name spec

WORKSPACE, container/BUILD, contrib/BUILD, docker/util/BUILD, python/image.bzl, testdata/BUILD, testdata/test/BUILD, tests/container/python/BUILD
```
common --@rules_python//python/config_settings:bootstrap_impl=script
```
=> Load py symbols from @rules_python
